Repository rudderlabs/rudder-transformer, pull requests merged in 2021-06, with the labels that each got.

#644 add attributes map creation for pubsub
  __tests__/data/googlepubsub_input.json
  __tests__/data/googlepubsub_output.json
  v0/destinations/googlepubsub/transform.js
  v0/destinations/googlepubsub/util.js
Labels: enhancement, wip

#658 braze batch identity fix for earlier batches(after split)
  v0/destinations/braze/transform.js
Labels: bug

#656 Dest gainsight px
  __mocks__/axios.js
  __mocks__/data/gainsight_px/response.json
  __mocks__/gainsight_px.mock.js
  __tests__/data/gainsight_px_input.json
  __tests__/data/gainsight_px_output.json
  __tests__/data/gainsight_px_router_input.json
  __tests__/data/gainsight_px_router_output.json
  __tests__/gainsight_px.test.js
  features.json
  v0/destinations/gainsight_px/config.js
  v0/destinations/gainsight_px/data/GainsightPX_Group.json
  v0/destinations/gainsight_px/data/GainsightPX_Identify.json
  v0/destinations/gainsight_px/data/GainsightPX_Track.json
  v0/destinations/gainsight_px/transform.js
  v0/destinations/gainsight_px/util.js
  v0/util/index.js
Labels: wip
