Repository rudderlabs/rudder-transformer, pull requests merged in 2021-11, with the labels that each got.

#826 Iterable support
  __tests__/data/iterable_input.json
  __tests__/data/iterable_output.json
  v0/destinations/iterable/transform.js
Labels: Ready For Review

#843 Customer.io:feature : alias support added
  v0/destinations/customerio/config.js
  v0/destinations/customerio/transform.js
Labels: Ready For Review

#850 Feat: Added library key support for Amplitude
  __tests__/data/am_batch_input.json
  __tests__/data/am_batch_output.json
  __tests__/data/am_output.json
  __tests__/data/am_router_output.json
  v0/destinations/am/transform.js
Labels: enhancement

#857 Feat: Added library key support for Amplitude
  __tests__/data/am_batch_input.json
  __tests__/data/am_batch_output.json
  __tests__/data/am_output.json
  __tests__/data/am_router_output.json
  util/stats.js
  v0/destinations/am/transform.js
  versionedRouter.js
Labels: enhancement

#794 Sendgrid Destination
  __tests__/data/sendgrid_input.json
  __tests__/data/sendgrid_output.json
  __tests__/data/sendgrid_router_input.json
  __tests__/data/sendgrid_router_output.json
  __tests__/sendgrid.test.js
  constants/destinationCanonicalNames.js
  v0/destinations/sendgrid/config.js
  v0/destinations/sendgrid/data/SendgridTrack.json
  v0/destinations/sendgrid/transform.js
  v0/destinations/sendgrid/util.js
Labels: Ready For Review

#863 HS - feat: optimize "properties" endpoint
  v0/destinations/hs/transform.js
Labels: enhancement, Ready For Review

#864 Feat : Destination Sendgrid
  __tests__/braze.test.js
  __tests__/data/braze_response_input.json
  __tests__/data/braze_response_output.json
  __tests__/data/marketo_response_input.json
  __tests__/data/marketo_response_output.json
  __tests__/data/sendgrid_input.json
  __tests__/data/sendgrid_output.json
  __tests__/data/sendgrid_router_input.json
  __tests__/data/sendgrid_router_output.json
  __tests__/data/versioned_response_heap_input.json
  __tests__/data/versioned_response_heap_output.json
  __tests__/marketo.test.js
  __tests__/sanity.test.js
  __tests__/sendgrid.test.js
  __tests__/versionedRouter.test.js
  adapters/networkhandler/genericNetworkResponseHandler.js
  adapters/utils/networkUtils.js
  constants/destinationCanonicalNames.js
  package.json
  v0/destinations/am/transform.js
  v0/destinations/braze/networkResponseHandler.js
  v0/destinations/braze/transform.js
  v0/destinations/ga/transform.js
  v0/destinations/hs/transform.js
  v0/destinations/marketo/networkResponseHandler.js
  v0/destinations/marketo/transform.js
  v0/destinations/sendgrid/config.js
  v0/destinations/sendgrid/data/SendgridTrack.json
  v0/destinations/sendgrid/transform.js
  v0/destinations/sendgrid/util.js
  v0/util/error.js
  v0/util/index.js
  versionedRouter.js
Labels: ready for merge

#858 Bug: Included check for payload.user and userEmail for Zendesk
  __tests__/data/zendesk_input.json
  __tests__/data/zendesk_output.json
  v0/destinations/zendesk/transform.js
Labels: Ready For Review, bug fix

#861 Bug Fix: added check for traits for Amplitude
  __tests__/data/am_input.json
  __tests__/data/am_output.json
  v0/destinations/am/transform.js
Labels: Ready For Review, bug fix

#867 Added json support for validation errors.
  __tests__/azure_synapse.test.js
  __tests__/bq.test.js
  __tests__/clickhouse.test.js
  __tests__/mssql.test.js
  __tests__/postgres.test.js
  __tests__/rs.test.js
  __tests__/s3_datalake.test.js
  __tests__/snowflake.test.js
  v0/destinations/azure_synapse/transform.js
  v0/destinations/bq/transform.js
  v0/destinations/clickhouse/transform.js
  v0/destinations/mssql/transform.js
  v0/destinations/postgres/transform.js
  v0/destinations/rs/transform.js
  v0/destinations/s3_datalake/transform.js
  v0/destinations/snowflake/transform.js
  warehouse/index.js
Labels: Ready For Review
