Repository rudderlabs/rudder-transformer, pull requests merged in 2021-12, with the labels that each got.

#869 Bug: Included check for payload.user and userEmail for Zendesk
  __tests__/data/zendesk_input.json
  __tests__/data/zendesk_output.json
  v0/destinations/zendesk/transform.js
Labels: Ready For Review

#871 Bug: Included check for payload.user and userEmail for Zendesk
  __tests__/data/zendesk_input.json
  __tests__/data/zendesk_output.json
  v0/destinations/zendesk/transform.js
Labels: Ready For Review

#856 Test Router with latest response transform changes
  __mocks__/axios.js
  __mocks__/data/profitwell/response.json
  __mocks__/profitwell.mock.js
  __tests__/data/profitwell_input.json
  __tests__/data/profitwell_output.json
  __tests__/data/profitwell_router_input.json
  __tests__/data/profitwell_router_output.json
  __tests__/profitwell.test.js
  adapters/network.js
  destTransformer.js
  features.json
  routerUtils.js
  testRouter.js
  util/customTransforrmationsStore-v1.js
  util/customTransforrmationsStore.js
  v0/destinations/profitwell/config.js
  v0/destinations/profitwell/data/CreateSubscription.json
  v0/destinations/profitwell/data/UpdateSubscription.json
  v0/destinations/profitwell/transform.js
  v0/destinations/profitwell/utils.js
  versionedRouter.js
Labels: WIP, DO NOT MERGE

#865 AM - fix: add additional properties support
  __tests__/data/am_input.json
  __tests__/data/am_output.json
  __tests__/data/am_router_output.json
  v0/destinations/am/data/AmplitudeDefaultConfig.json
  v0/destinations/am/transform.js
Labels: Ready For Review, bug fix

#414 Braze Currents
  __tests__/braze_source.test.js
  __tests__/data/braze_source_input.json
  __tests__/data/braze_source_output.json
  v0/sources/braze/eventMapping.json
  v0/sources/braze/ignore.json
  v0/sources/braze/mapping.json
  v0/sources/braze/transform.js
  v0/sources/message.js
  v0/util/index.js
Labels: ready for merge

#888 Ampplitude: addressing CFD for revenue field , when the value is 0
  __tests__/data/am_input.json
  __tests__/data/am_output.json
  v0/destinations/am/transform.js
Labels: bug fix

#887 Add: device object initialization for appsflyer source
  __tests__/data/appsflyer_source_input.json
  __tests__/data/appsflyer_source_output.json
  v0/sources/appsflyer/transform.js
Labels: Ready For Review

#893 Update test router
  testRouter.js
Labels: DO NOT MERGE

#899 Amplitude: add location in common config
  __tests__/data/am_input.json
  __tests__/data/am_output.json
  v0/destinations/am/config.js
  v0/destinations/am/data/AmplitudeCommonConfig.json
  v0/destinations/am/data/AmplitudeDefaultConfig.json
  v0/destinations/am/transform.js
Labels: bug, Ready For Review

#897 Network layer updates
  __mocks__/data/am/proxy_response.json
  __mocks__/data/braze/proxy_response.json
  __mocks__/data/marketo/proxy_response.json
  __mocks__/network.js
  __tests__/braze.test.js
  __tests__/data/braze_proxy_input.json
  __tests__/data/braze_proxy_output.json
  __tests__/data/braze_response_input.json
  __tests__/data/braze_response_output.json
  __tests__/data/marketo_proxy_input.json
  __tests__/data/marketo_proxy_output.json
  __tests__/data/marketo_response_input.json
  __tests__/data/marketo_response_output.json
  __tests__/data/proxy_input.json
  __tests__/data/proxy_output.json
  __tests__/data/versioned_response_heap_input.json
  __tests__/data/versioned_response_heap_output.json
  __tests__/marketo.test.js
  __tests__/proxy.test.js
  __tests__/versionedRouter.test.js
  adapters/network.js
  adapters/networkHandlerFactory.js
  adapters/networkhandler/genericNetworkHandler.js
  adapters/utils/networkUtils.js
  destTransformer.js
  routerUtils.js
  testRouter.js
  v0/destinations/braze/util.js
  v0/destinations/klaviyo/transform.js
  v0/destinations/marketo/networkResponseHandler.js
  v0/destinations/marketo/transform.js
  v0/destinations/marketo/util.js
  v0/destinations/trengo/transform.js
  versionedRouter.js
Labels: DO NOT MERGE

#904 Feat: Klaviyo ecommerce Specs
  __tests__/data/klaviyo_input.json
  __tests__/data/klaviyo_output.json
  v0/destinations/klaviyo/config.js
  v0/destinations/klaviyo/data/AddedToCart.json
  v0/destinations/klaviyo/data/Items.json
  v0/destinations/klaviyo/data/StartedCheckout.json
  v0/destinations/klaviyo/data/ViewedProduct.json
  v0/destinations/klaviyo/transform.js
Labels: Ready For Review

#907 Klaviyo ecom specs + Network Layer
  __mocks__/data/am/proxy_response.json
  __mocks__/data/braze/proxy_response.json
  __mocks__/data/marketo/proxy_response.json
  __mocks__/network.js
  __tests__/braze.test.js
  __tests__/data/braze_proxy_input.json
  __tests__/data/braze_proxy_output.json
  __tests__/data/braze_response_input.json
  __tests__/data/braze_response_output.json
  __tests__/data/klaviyo_input.json
  __tests__/data/klaviyo_output.json
  __tests__/data/marketo_proxy_input.json
  __tests__/data/marketo_proxy_output.json
  __tests__/data/marketo_response_input.json
  __tests__/data/marketo_response_output.json
  __tests__/data/proxy_input.json
  __tests__/data/proxy_output.json
  __tests__/data/versioned_response_heap_input.json
  __tests__/data/versioned_response_heap_output.json
  __tests__/marketo.test.js
  __tests__/proxy.test.js
  __tests__/versionedRouter.test.js
  adapters/network.js
  adapters/networkHandlerFactory.js
  adapters/networkhandler/genericNetworkHandler.js
  adapters/utils/networkUtils.js
  destTransformer.js
  routerUtils.js
  testRouter.js
  util/ivmFactory.js
  v0/destinations/braze/util.js
  v0/destinations/klaviyo/config.js
  v0/destinations/klaviyo/data/AddedToCart.json
  v0/destinations/klaviyo/data/Items.json
  v0/destinations/klaviyo/data/StartedCheckout.json
  v0/destinations/klaviyo/data/ViewedProduct.json
  v0/destinations/klaviyo/transform.js
  v0/destinations/marketo/networkResponseHandler.js
  v0/destinations/marketo/transform.js
  v0/destinations/marketo/util.js
  v0/destinations/trengo/transform.js
  versionedRouter.js
Labels: Ready For Review

#835 Feat: Destination Ometria
  __tests__/data/ometria_batch_input.json
  __tests__/data/ometria_batch_output.json
  __tests__/data/ometria_input.json
  __tests__/data/ometria_output.json
  __tests__/ometria.test.js
  constants/destinationCanonicalNames.js
  features.json
  v0/destinations/ometria/config.js
  v0/destinations/ometria/data/OmetriaContact.json
  v0/destinations/ometria/data/OmetriaCustomEvent.json
  v0/destinations/ometria/data/OmetriaLineitems.json
  v0/destinations/ometria/data/OmetriaOrder.json
  v0/destinations/ometria/data/OmetriaVariant.json
  v0/destinations/ometria/networkResponseHandler.js
  v0/destinations/ometria/transform.js
  v0/destinations/ometria/util.js
Labels: WIP

#903 Update test router
  __tests__/data/test_router_input.json
  __tests__/data/test_router_output.json
  __tests__/testRouter.test.js
  package.json
  routerUtils.js
  testRouter.js
Labels: DO NOT MERGE

#925 feat: add all apple family support
  __tests__/data/adj_input.json
  __tests__/data/adj_output.json
  __tests__/data/am_input.json
  __tests__/data/am_output.json
  __tests__/data/appsflyer_source_input.json
  __tests__/data/appsflyer_source_output.json
  __tests__/data/branch_input.json
  __tests__/data/branch_output.json
  __tests__/data/clevertap_input.json
  __tests__/data/clevertap_output.json
  __tests__/data/fb_input.json
  __tests__/data/fb_output.json
  __tests__/data/iterable_input.json
  __tests__/data/iterable_output.json
  __tests__/data/kochava_input.json
  __tests__/data/kochava_output.json
  __tests__/data/mp_input.json
  __tests__/data/mp_output.json
  v0/destinations/adj/transform.js
  v0/destinations/af/transform.js
  v0/destinations/am/transform.js
  v0/destinations/branch/transform.js
  v0/destinations/clevertap/transform.js
  v0/destinations/fb/transform.js
  v0/destinations/iterable/transform.js
  v0/destinations/kochava/transform.js
  v0/destinations/mp/transform.js
  v0/sources/appsflyer/transform.js
  v0/util/index.js
Labels: enhancement, Ready For Review

#929 Branch CFD: OS name missing
  __tests__/data/branch_input.json
  __tests__/data/branch_output.json
  __tests__/data/branch_router_input.json
  __tests__/data/branch_router_output.json
  v0/destinations/branch/transform.js
Labels: Ready For Review, bug fix
