Repository rudderlabs/rudder-transformer, pull requests merged in 2022-01, with the labels that each got.

#906 Event Type Support for Tracking Plan
  __tests__/eventValidation.test.js
  __tests__/trackingPlan.test.js
  util/eventValidation.js
  util/trackingPlan.js
Labels: Ready For Review

#866 Feat lakes
  v0/destinations/azure_datalake/transform.js
  v0/destinations/deltalake/transform.js
  v0/destinations/gcs_datalake/transform.js
  warehouse/config/ReservedKeywords.json
  warehouse/config/helpers.js
  warehouse/index.js
  warehouse/v0/util.js
  warehouse/v1/util.js
Labels: Ready For Review

#836 deletion-api: added end point for deletion of users in versioned router
  __tests__/data/am_deleteUsers_proxy_input.json
  __tests__/data/am_deleteUsers_proxy_output.json
  __tests__/data/braze_deleteUsers_proxy_input.json
  __tests__/data/braze_deleteUsers_proxy_output.json
  __tests__/data/intercom_deleteUsers_proxy_input.json
  __tests__/data/intercom_deleteUsers_proxy_output.json
  __tests__/proxy.test.js
  v0/destinations/am/deleteUsers.js
  v0/destinations/braze/deleteUsers.js
  v0/destinations/intercom/deleteUsers.js
  versionedRouter.js
Labels: DO NOT MERGE

#935 Kochava - correct idfv keyword name
  __tests__/data/kochava_output.json
  v0/destinations/kochava/transform.js
Labels: bug fix

#837 Profitwell Integration
  __mocks__/axios.js
  __mocks__/data/profitwell/response.json
  __mocks__/profitwell.mock.js
  __tests__/data/profitwell_input.json
  __tests__/data/profitwell_output.json
  __tests__/data/profitwell_router_input.json
  __tests__/data/profitwell_router_output.json
  __tests__/profitwell.test.js
  features.json
  v0/destinations/profitwell/config.js
  v0/destinations/profitwell/data/CreateSubscription.json
  v0/destinations/profitwell/data/UpdateSubscription.json
  v0/destinations/profitwell/transform.js
  v0/destinations/profitwell/utils.js
Labels: new-integration

#945 AF bugFix : removed default value 'all' from sharingFilter
  __tests__/appsFlyer.test.js
  __tests__/data/af_input.json
  __tests__/data/af_output.json
  __tests__/data/af_router_input.json
  __tests__/data/af_router_output.json
  v0/destinations/af/transform.js
Labels: Ready For Review

#936 Bugfix: To support field with mapping in dynamic config
  __tests__/data/dynamicConfig_input.json
  __tests__/data/dynamicConfig_output.json
  __tests__/data/versioned_processor_heap_input.json
  __tests__/data/versioned_processor_heap_output.json
  __tests__/dynamicConfig.test.js
  util/dynamicConfig.js
Labels: Ready For Review

#924 Shopify source v2
  __tests__/data/shopify_source_input.json
  __tests__/data/shopify_source_output.json
  __tests__/ometria.test.js
  __tests__/shopify_source.test.js
  v0/destinations/ometria/data/OmetriaLineitems.json
  v0/sources/shopify/config.js
  v0/sources/shopify/data/identifyMapping.json
  v0/sources/shopify/data/lineItemsMapping.json
  v0/sources/shopify/data/mapping.json
  v0/sources/shopify/data/productMapping.json
  v0/sources/shopify/transform.js
  v0/sources/shopify/util.js
Labels: WIP, DO NOT MERGE
