Repository rudderlabs/rudder-transformer, pull requests merged in 2022-04, with the labels that each got.

#1090 Zendesk : name require, identify
  __tests__/data/zendesk_output.json
  v0/destinations/zendesk/data/ZDIdentifyConfig.json
Labels: Ready For Review, bug fix

#1091 [Mixpanle] Standardizing event names for Page and Screen calls
  __tests__/data/mp_output.json
  __tests__/data/mp_router_output.json
  v0/destinations/mp/transform.js
Labels: Ready For Review

#1085 Mailchimp: add email validation
  __mocks__/data/mailchimp/response.json
  __mocks__/mailchimp.mock.js
  __tests__/data/mailchimp_input.json
  __tests__/data/mailchimp_output.json
  v0/destinations/mailchimp/transform.js
Labels: Ready For Review, bug fix

#1094 Facebook Pixel event_id discrepancy
  __tests__/data/facebook_pixel_output.json
  __tests__/data/facebook_pixel_router_output.json
  v0/destinations/facebook_pixel/data/FBPIXELCommonConfig.json
Labels: Ready For Review

#1089 am-eu-support
  __tests__/data/am_batch_input.json
  __tests__/data/am_batch_output.json
  __tests__/data/am_input.json
  __tests__/data/am_output.json
  v0/destinations/am/config.js
  v0/destinations/am/transform.js
Labels: Ready For Review

#1075 VDM-Marketo changes
  __tests__/data/marketo_input.json
  __tests__/data/marketo_output.json
  v0/destinations/marketo/transform.js
  v0/util/index.js
Labels: WIP, DO NOT MERGE

#1097 Transformer CDK: solving cdk new destination onboarding problem
  versionedRouter.js
Labels: Ready For Review

#1107 Airship: Use API key authorization
  __tests__/data/airship_input.json
  __tests__/data/airship_output.json
  __tests__/data/airship_router_input.json
  __tests__/data/airship_router_output.json
  v0/destinations/airship/transform.js
Labels: Ready For Review

#1102 feature(new integration):DCM cloud mode Integration onboarding
  __tests__/cdk_postMapper/dcm_floodlight.test.js
  __tests__/data/dcm_floodlight_input.json
  __tests__/data/dcm_floodlight_output.json
  __tests__/dcm_floodlight.test.js
  cdk/dcm_floodlight/config.yaml
  cdk/dcm_floodlight/mapping/track.yaml
  cdk/dcm_floodlight/transform.js
  constants/destinationCanonicalNames.js
Labels: new-integration, Ready For Review

#1113 feature(enhancement): Blueshift update group call
  __mocks__/axios.js
  __mocks__/data/blueshift/response.json
  __tests__/data/blueshift_input.json
  __tests__/data/blueshift_output.json
  __tests__/data/blueshift_router_input.json
  __tests__/data/blueshift_router_output.json
  v0/destinations/blueshift/data/blueshiftGroupConfig.json
  v0/destinations/blueshift/data/blueshiftTrackConfig.json
  v0/destinations/blueshift/transform.js
Labels: Ready For Review

#1119 bugfix(google adwords enhanced conversions):updating track config
  __tests__/data/google_adwords_enhanced_conversions_input.json
  __tests__/data/google_adwords_enhanced_conversions_output.json
  __tests__/data/google_adwords_enhanced_conversions_proxy_input.json
  __tests__/data/google_adwords_enhanced_conversions_router_input.json
  v0/destinations/google_adwords_enhanced_conversions/data/trackConfig.json
Labels: Ready For Review

#1122 feature(AM) : event_id support
  __tests__/data/am_input.json
  __tests__/data/am_output.json
  v0/destinations/am/data/AmplitudeAliasConfig.json
  v0/destinations/am/data/AmplitudeDefaultConfig.json
  v0/destinations/am/data/AmplitudeGroupConfig.json
  v0/destinations/am/data/AmplitudeIdentifyConfig.json
  v0/destinations/am/data/AmplitudePageConfig.json
  v0/destinations/am/data/AmplitudeScreenConfig.json
  v0/destinations/am/transform.js
  v0/destinations/am/utils.js
Labels: enhancement

#1129 feature(new integration): Iterable source onboarding
  __tests__/data/iterable_source_input.json
  __tests__/data/iterable_source_output.json
  __tests__/iterable_source.test.js
  v0/sources/iterable/mapping.json
  v0/sources/iterable/transform.js
Labels: Ready For Review

#1130 feature(new integration): GA4 cloud mode Integration onboarding
  __tests__/data/ga4_input.json
  __tests__/data/ga4_output.json
  __tests__/ga4.test.js
  adapters/networkHandlerFactory.js
  v0/destinations/ga4/config.js
  v0/destinations/ga4/data/GA4CartSharedConfig.json
  v0/destinations/ga4/data/GA4CartViewedConfig.json
  v0/destinations/ga4/data/GA4CheckoutStartedConfig.json
  v0/destinations/ga4/data/GA4CommonConfig.json
  v0/destinations/ga4/data/GA4EarnVirtualCurrencyConfig.json
  v0/destinations/ga4/data/GA4GenerateLeadConfig.json
  v0/destinations/ga4/data/GA4GroupConfig.json
  v0/destinations/ga4/data/GA4ItemsConfig.json
  v0/destinations/ga4/data/GA4LevelUpConfig.json
  v0/destinations/ga4/data/GA4LoginConfig.json
  v0/destinations/ga4/data/GA4OrderCompletedConfig.json
  v0/destinations/ga4/data/GA4OrderRefundedConfig.json
  v0/destinations/ga4/data/GA4PaymentInfoEnteredConfig.json
  v0/destinations/ga4/data/GA4PostScoreConfig.json
  v0/destinations/ga4/data/GA4ProductAddedConfig.json
  v0/destinations/ga4/data/GA4ProductAddedToWishlistConfig.json
  v0/destinations/ga4/data/GA4ProductClickedConfig.json
  v0/destinations/ga4/data/GA4ProductListViewedConfig.json
  v0/destinations/ga4/data/GA4ProductRemovedConfig.json
  v0/destinations/ga4/data/GA4ProductSharedConfig.json
  v0/destinations/ga4/data/GA4ProductViewedConfig.json
  v0/destinations/ga4/data/GA4ProductsSearchedConfig.json
  v0/destinations/ga4/data/GA4PromotionClickedConfig.json
  v0/destinations/ga4/data/GA4PromotionViewedConfig.json
  v0/destinations/ga4/data/GA4SelectContentConfig.json
  v0/destinations/ga4/data/GA4SignUpConfig.json
  v0/destinations/ga4/data/GA4SpendVirtualCurrencyConfig.json
  v0/destinations/ga4/data/GA4UnlockAchievementConfig.json
  v0/destinations/ga4/data/GA4ViewSearchResultsConfig.json
  v0/destinations/ga4/transform.js
  v0/destinations/ga4/utils.js
  v0/util/index.js
Labels: new-integration, Ready For Review

#1135 bugfix(misc):update price check in destination
  v0/destinations/am/transform.js
  v0/destinations/drip/util.js
  v0/destinations/monetate/transform.js
  v0/destinations/ometria/util.js
Labels: Ready For Review, bug fix
