Repository rudderlabs/rudder-transformer, pull requests merged in 2022-06, with the labels that each got.

#1204 bugfix(personalize): allowing non string properties to personalize
  __tests__/data/personalize_input.json
  __tests__/data/personalize_output.json
  v0/destinations/personalize/transform.js
Labels: Ready For Review, bug fix

#1205 bugfix(integration):Mixpanel update error message for group api
  __tests__/data/mp_output.json
  v0/destinations/mp/transform.js
Labels: enhancement

#1207 bugfix(integration): adjust adding functionality for sending ip address
  __tests__/data/adj_output.json
  __tests__/data/adj_router_output.json
  v0/destinations/adj/data/ADJUSTTrackConfig.json
Labels: Ready for Review

#1193 chore(warehouse): tracking plan validation compatiblility for spread sheet plugin
  __tests__/eventValidation.test.js
  util/eventValidation.js
Labels: Ready for Review

#1211 bugfix(Integration): For Zendesk, deleted the unnecessary userId check for sendGroupCallsWithoutUserId true
  __tests__/data/zendesk_input.json
  __tests__/data/zendesk_output.json
  v0/destinations/zendesk/transform.js
Labels: Ready for Review

#1199 fix(router): Adding counter stats to proxy request
  versionedRouter.js
Labels: NETWORK LAYER

#1231 Pass full payload to Attribution
  __tests__/data/attribution_output.json
  v0/destinations/attribution/transform.js
Labels: ready for merge

#1232 Bugfix(integration): DCM - add support to take custom variable from properties
  __tests__/cdk_postMapper/dcm_floodlight.test.js
  __tests__/data/dcm_floodlight_input.json
  __tests__/data/dcm_floodlight_output.json
  cdk/dcm_floodlight/config.js
  cdk/dcm_floodlight/config.yaml
  cdk/dcm_floodlight/mapping/DCMFloodlightConfig.yaml
  cdk/dcm_floodlight/transform.js
  constants/index.js
Labels: bug fix

#1236 fix(integrations): Braze adding dynamic support for eu data center
  v0/destinations/braze/transform.js
Labels: Ready for Review

#1214 Fix a few issues with the Facebook App Events destination
  __tests__/data/fb_input.json
  __tests__/data/fb_output.json
  v0/destinations/fb/data/FbAppBasicMapping.json
  v0/destinations/fb/transform.js
Labels: ready for merge

#1241 bugfix: Fix for transformerProxy "FORM" format
  __mocks__/data/facebook_pixel/proxy_response.json
  __mocks__/network.js
  __tests__/data/proxy_input.json
  __tests__/data/proxy_output.json
  adapters/network.js
Labels: bug fix

#1206 feature(singular-cloud-mode): Onboard new integration
  __tests__/data/singular.json
  __tests__/data/singular_router_input.json
  __tests__/data/singular_router_output.json
  __tests__/singular.test.js
  v0/destinations/singular/config.js
  v0/destinations/singular/data/SINGULARAndroidEventConfig.json
  v0/destinations/singular/data/SINGULARAndroidSessionConfig.json
  v0/destinations/singular/data/SINGULAREventProductConfig.json
  v0/destinations/singular/data/SINGULARIosEventConfig.json
  v0/destinations/singular/data/SINGULARIosSessionConfig.json
  v0/destinations/singular/transform.js
  v0/destinations/singular/util.js
Labels: new-integration, ready for merge

#1259 Bugfix(integration):Adobe Analytics Page and Screen Calls expecting event field
  __tests__/data/adobe_analytics_input.json
  __tests__/data/adobe_analytics_output.json
  v0/destinations/adobe_analytics/transform.js
Labels: bug fix
