Repository rudderlabs/rudder-transformer, pull requests merged in 2022-08, with the labels that each got.

#1307 Feature(integration): Facebook Pixel Mandatory properties fix
  __tests__/data/facebook_pixel_input.json
  __tests__/data/facebook_pixel_output.json
  v0/destinations/facebook_pixel/transform.js
  v0/destinations/facebook_pixel/utils.js
Labels: Ready for Review, bug fix

#1315 Feature(integration): Facebook Custom Audience API Version Upgrade
  __tests__/data/fb_custom_audience.json
  __tests__/data/fb_custom_audience_input.json
  __tests__/data/fb_custom_audience_output.json
  __tests__/data/fb_custom_audience_router.json
  __tests__/data/fb_custom_audience_router_input.json
  __tests__/data/fb_custom_audience_router_output.json
  __tests__/fb_custom_audience.test.js
  v0/destinations/fb_custom_audience/config.js
Labels: enhancement, Ready for Review

#1323 Description for Test Cases of Fb Audience Updated and Coverage Improved
  __tests__/data/fb_custom_audience.json
Labels: enhancement, Ready for Review

#1281 feature(integration): HS - revamp and add new API support
  __mocks__/axios.js
  __mocks__/data/hs/response.json
  __mocks__/hs.mock.js
  __tests__/data/hs.json
  __tests__/data/hs_input.json
  __tests__/data/hs_output.json
  __tests__/data/hs_router_input.json
  __tests__/data/hs_router_input_legacy.json
  __tests__/data/hs_router_input_rETL.json
  __tests__/data/hs_router_output.json
  __tests__/data/hs_router_output_legacy.json
  __tests__/data/hs_router_output_rETL.json
  __tests__/hubspot.test.js
  adapters/utils/networkUtils.js
  v0/destinations/hs/HSTransform-v1.js
  v0/destinations/hs/HSTransform-v2.js
  v0/destinations/hs/config.js
  v0/destinations/hs/data/HSCommonConfig.json
  v0/destinations/hs/data/HSIdentifyConfig.json
  v0/destinations/hs/data/HSTrackConfig.json
  v0/destinations/hs/data/HSTrackPropertiesConfig.json
  v0/destinations/hs/transform.js
  v0/destinations/hs/util.js
Labels: enhancement, Ready for Review

#1310 feature(new integration): Canny Source Onboarding
  __tests__/canny_source.test.js
  __tests__/data/canny_source_input.json
  __tests__/data/canny_source_output.json
  v0/sources/canny/authorMapping.json
  v0/sources/canny/transform.js
  v0/sources/canny/util.js
  v0/sources/canny/voterMapping.json
Labels: new-integration

#1312 feature (new Integration): OneSignal(cloud mode) destination Onboarding
  __tests__/data/one_signal.json
  __tests__/data/one_signal_router_input.json
  __tests__/data/one_signal_router_output.json
  __tests__/one_signal.test.js
  constants/destinationCanonicalNames.js
  v0/destinations/one_signal/config.js
  v0/destinations/one_signal/data/OneSignalIdentifyConfig.json
  v0/destinations/one_signal/transform.js
  v0/destinations/one_signal/util.js
Labels: new-integration

#1311 feature(new integration): Canny Destination Onboarding
  __mocks__/axios.js
  __mocks__/canny.mock.js
  __mocks__/data/canny/response.json
  __tests__/canny.test.js
  __tests__/data/canny.json
  constants/destinationCanonicalNames.js
  features.json
  v0/destinations/canny/config.js
  v0/destinations/canny/data/createPostConfig.json
  v0/destinations/canny/data/createVoteConfig.json
  v0/destinations/canny/data/identifyConfig.json
  v0/destinations/canny/transform.js
  v0/destinations/canny/util.js
Labels: new-integration

#1279 feature(integration): GA4 - add optional parameters for user reports
  __tests__/data/ga4.json
  v0/destinations/ga4/config.js
  v0/destinations/ga4/data/GA4IdentifyGroupCommonParamsConfig.json
  v0/destinations/ga4/data/GA4TrackPageCommonParamsConfig.json
  v0/destinations/ga4/transform.js
  v0/destinations/ga4/utils.js
Labels: enhancement

#1341 enhancement(integration): posthog new properties added
  __tests__/data/posthog.json
  __tests__/data/posthog_input.json
  __tests__/data/posthog_output.json
  __tests__/data/posthog_router.json
  __tests__/data/posthog_router_input.json
  __tests__/data/posthog_router_output.json
  __tests__/posthog.test.js
  v0/destinations/posthog/data/PHPropertiesConfig.json
Labels: Ready for Review

#1339 feature (new integration): Onboarding Google Cloud Function
  __tests__/data/google_cloud_function_router_input.json
  __tests__/data/google_cloud_function_router_output.json
  __tests__/google_cloud_function.test.js
  features.json
  v0/destinations/google_cloud_function/config.js
  v0/destinations/google_cloud_function/transform.js
  v0/destinations/google_cloud_function/util.js
Labels: Ready for Review

#1335 feature(new integration): Wootric Destination Onboarding
  __mocks__/axios.js
  __mocks__/data/wootric/response.json
  __mocks__/network.js
  __mocks__/wootric.mock.js
  __tests__/data/wootric.json
  __tests__/data/wootric_router_input.json
  __tests__/data/wootric_router_output.json
  __tests__/wootric.test.js
  constants/destinationCanonicalNames.js
  features.json
  v0/destinations/wootric/config.js
  v0/destinations/wootric/data/createDeclineConfig.json
  v0/destinations/wootric/data/createResponseConfig.json
  v0/destinations/wootric/data/identifyConfig.json
  v0/destinations/wootric/transform.js
  v0/destinations/wootric/util.js
Labels: Ready for Review

#1364 feature(wootric): Added User properties patching
  __mocks__/data/wootric/response.json
  __mocks__/wootric.mock.js
  __tests__/data/wootric.json
  __tests__/data/wootric_router_input.json
  __tests__/data/wootric_router_output.json
  v0/destinations/wootric/data/identifyConfig.json
  v0/destinations/wootric/transform.js
  v0/destinations/wootric/util.js
Labels: Ready for Review

#1353 Feature ( new integration ): Mautic Destination Onboarding
  __mocks__/axios.js
  __mocks__/data/mautic/response.json
  __mocks__/network.js
  __tests__/data/mautic.json
  __tests__/data/mautic_router_input.json
  __tests__/data/mautic_router_output.json
  __tests__/mautic.test.js
  constants/destinationCanonicalNames.js
  v0/destinations/mautic/config.js
  v0/destinations/mautic/data/MauticIdentifyConfig.json
  v0/destinations/mautic/transform.js
  v0/destinations/mautic/utils.js
  v0/util/data/GenericFieldMapping.json
  v0/util/index.js
Labels: new-integration, Ready for Review
