Repository rudderlabs/rudder-transformer, pull requests merged in 2022-11, with the labels that each got.

#1530 feat(integration): user defined event support for pinterest conversions destination
  __tests__/data/pinterest_tag_output.json
  cdk/v2/destinations/pinterest_tag/procWorkflow.yaml
  v0/destinations/pinterest_tag/utils.js
Labels: enhancement

#1488 feat: added multitopic support for kafka
  __tests__/data/kafka_batch_input.json
  __tests__/data/kafka_batch_output.json
  constants/destinationCanonicalNames.js
  v0/destinations/azure_event_hub/transform.js
  v0/destinations/confluent_cloud/transform.js
  v0/destinations/kafka/transform.js
  versionedRouter.js
Labels: work-in-progress

#1443 feat(new integration): onboarding snapchat custom audience
  __mocks__/data/snapchat_custom_audience/proxy_response.json
  __mocks__/network.js
  __tests__/data/snapchat_custom_audience.json
  __tests__/data/snapchat_custom_audience_proxy_input.json
  __tests__/data/snapchat_custom_audience_proxy_output.json
  __tests__/data/snapchat_custom_audience_router_input.json
  __tests__/data/snapchat_custom_audience_router_output.json
  __tests__/proxy.test.js
  __tests__/snapchat_custom_audience.test.js
  adapters/networkHandlerFactory.js
  constants/destinationCanonicalNames.js
  features.json
  v0/destinations/snapchat_custom_audience/config.js
  v0/destinations/snapchat_custom_audience/transform.js
  v0/destinations/snapchat_custom_audience/utils.js
Labels: new-integration

#1538 fix : amplitude api endpoint version update
  __tests__/data/am_batch_input.json
  __tests__/data/am_batch_output.json
  __tests__/data/am_output.json
  __tests__/data/am_router_output.json
  v0/destinations/am/config.js
Labels: Ready for Review

#1537 feature: batch user deletion support for mixpanel and clevertap
  __tests__/data/clevertap_deleteUsers_proxy_input.json
  __tests__/data/clevertap_deleteUsers_proxy_output.json
  __tests__/data/mp_deleteUsers_proxy_input.json
  __tests__/data/mp_deleteUsers_proxy_output.json
  v0/destinations/clevertap/config.js
  v0/destinations/clevertap/deleteUsers.js
  v0/destinations/mp/config.js
  v0/destinations/mp/deleteUsers.js
Labels: Ready for Review

#1548 fix(destination): user-defined event support in pinterest
  __tests__/data/pinterest_tag_output.json
  cdk/v2/destinations/pinterest_tag/procWorkflow.yaml
  v0/destinations/pinterest_tag/utils.js
Labels: enhancement, Ready for Review

#1527 feat: support custom webhooks in auth0 source transformer
  __tests__/auth0_source.test.js
  __tests__/data/auth0_source.json
  __tests__/data/auth0_source_input.json
  __tests__/data/auth0_source_output.json
  v0/sources/auth0/mapping.json
  v0/sources/auth0/transform.js
  v0/sources/auth0/util.js
Labels: Ready for Review

#1549 fix: ecom events properties mapping correction
  __tests__/data/klaviyo.json
  v0/destinations/klaviyo/transform.js
Labels: Ready for Review, bug fix

#1554 feat(destination): stringify the object and array for Clevertap
  __tests__/data/clevertap_output.json
  __tests__/data/clevertap_router_output.json
  v0/destinations/clevertap/transform.js
Labels: enhancement

#1553 feat(destination): support custom mapping with client_id for ga4 destination
  __tests__/data/ga4.json
  v0/destinations/ga4/transform.js
Labels: Ready for Review

#1539 feat(Zendesk): update identify call
  __mocks__/data/zendesk/response.json
  __tests__/data/zendesk_input.json
  __tests__/data/zendesk_output.json
  v0/destinations/zendesk/transform.js
Labels: enhancement

#1560 fix(destination): skip unix timestamp conversion if already being se…
  v0/util/index.js
Labels: bug fix

#1515 chore(transformation): adding user transformation builds separately
  .github/workflows/pr-builds.yml
  .github/workflows/saas-builds.yml
  Dockerfile-ut-func
Labels: Ready for Review

#1566 fix: typo in topic mapping for shopify source
  __tests__/data/shopify_source_input.json
  __tests__/data/shopify_source_output.json
  v0/sources/shopify/config.js
Labels: Ready for Review

#1567 fix: add test coverage for processMetadata function
  __tests__/azure_event_hub.test.js
  __tests__/confluent_cloud.test.js
  __tests__/data/azure_event_hub_with_metadata.json
  __tests__/data/confluent_cloud_with_metadata.json
  __tests__/data/kafka_with_metadata.json
  __tests__/kafka.test.js
  v0/destinations/azure_event_hub/transform.js
  v0/destinations/confluent_cloud/transform.js
Labels: Ready for Review

#1581 fix(destination): fix the flattening issue solve for ga4
  __tests__/data/ga4.json
  v0/destinations/ga4/utils.js
  v0/util/index.js
Labels: testing, bug fix

#1571 feat: sendgrid idetify and user deletion support
  __mocks__/axios.js
  __mocks__/data/sendgrid/response.json
  __mocks__/sendgrid.mock.js
  __tests__/data/sendgrid.json
  __tests__/data/sendgrid_batch.json
  __tests__/data/sendgrid_deleteUsers_proxy_input.json
  __tests__/data/sendgrid_deleteUsers_proxy_output.json
  __tests__/data/sendgrid_input.json
  __tests__/data/sendgrid_output.json
  __tests__/data/sendgrid_router.json
  __tests__/data/sendgrid_router_input.json
  __tests__/data/sendgrid_router_output.json
  __tests__/proxy.test.js
  __tests__/sendgrid.test.js
  features.json
  v0/destinations/sendgrid/config.js
  v0/destinations/sendgrid/data/SendgridIdentify.json
  v0/destinations/sendgrid/deleteUsers.js
  v0/destinations/sendgrid/transform.js
  v0/destinations/sendgrid/util.js
  v0/sources/auth0/transform.js
Labels: Ready for Review

#1594 feat(source): onboard satismeter as an event-stream
  __tests__/data/satismeter_source.json
  __tests__/satismeter_source.test.js
  v0/sources/satismeter/data/trackMapping.json
  v0/sources/satismeter/transform.js
  v0/util/index.js
Labels: new-integration, Ready for Review

#1593 refactor(existing destinations): error handling
  __tests__/data/clickup.json
  __tests__/data/clickup_router_output.json
  __tests__/data/mailjet.json
  __tests__/data/mautic.json
  __tests__/data/mautic_router_output.json
  __tests__/data/refiner.json
  v0/destinations/clickup/config.js
  v0/destinations/clickup/transform.js
  v0/destinations/clickup/util.js
  v0/destinations/june/transform.js
  v0/destinations/mailjet/transform.js
  v0/destinations/mautic/config.js
  v0/destinations/mautic/transform.js
  v0/destinations/mautic/utils.js
  v0/destinations/refiner/config.js
  v0/destinations/refiner/transform.js
  v0/destinations/refiner/utils.js
Labels: Ready for Review

#1606 fix(hubspot): legacy track api
  __tests__/data/hs_output.json
  v0/destinations/hs/HSTransform-v1.js
Labels: Ready for Review, bug fix

#1607 feat: ga4 hybrid mode suport
  constants/destinationCanonicalNames.js
  v0/destinations/ga4/transform.js
Labels: Ready for Review
