Repository rudderlabs/rudder-transformer, pull requests merged in 2022-03, with the labels that each got.

#1023 GA: url encoded bug
  __tests__/data/ga_output.json
  __tests__/data/ga_router_output.json
  v0/destinations/ga/transform.js
Labels: bug fix

#1024 Iterable bug issue
  __tests__/data/iterable_input.json
  __tests__/data/iterable_output.json
  v0/destinations/iterable/transform.js
Labels: bug fix

#1030 Facebook Pixel : formatrevenue function edited
  __tests__/data/facebook_pixel_input.json
  __tests__/data/facebook_pixel_output.json
  v0/destinations/facebook_pixel/transform.js
Labels: WIP, bug fix

#1025 Google Ads Audience - add deletion support
  __tests__/data/google_adwords_remarketing_lists_input.json
  __tests__/data/google_adwords_remarketing_lists_output.json
  __tests__/data/google_adwords_remarketing_lists_proxy_input.json
  __tests__/data/google_adwords_remarketing_lists_proxy_output.json
  __tests__/data/google_adwords_remarketing_lists_router_input.json
  __tests__/data/google_adwords_remarketing_lists_router_output.json
  v0/destinations/google_adwords_remarketing_lists/transform.js
  v0/destinations/google_adwords_remarketing_lists/util.js
Labels: enhancement, Ready For Review

#1038 fix group api in posthog
  v0/destinations/posthog/data/PHGroupConfig.json
  v0/destinations/posthog/transform.js
Labels: Ready For Review

#1047 Bug Fix: User ID is reset to empty string when it is falsy
  versionedRouter.js
Labels: Ready For Review, bug fix

#1046 update group call in posthog
  __tests__/data/posthog_input.json
  __tests__/data/posthog_output.json
  v0/destinations/posthog/config.js
  v0/destinations/posthog/data/PHGroupConfigOld.json
  v0/destinations/posthog/transform.js
Labels: Ready For Review

#1057 Heap: add additional params
  __tests__/data/heap_input.json
  __tests__/data/heap_output.json
  __tests__/data/heap_router_input.json
  __tests__/data/heap_router_output.json
  __tests__/data/versioned_processor_heap_output.json
  __tests__/data/versioned_router_heap_output.json
  v0/destinations/heap/data/HEAPIdentifyConfig.json
  v0/destinations/heap/data/HEAPTrackConfig.json
  v0/destinations/heap/transform.js
Labels: enhancement

#1065 Garl hotfix
  v0/destinations/google_adwords_remarketing_lists/transform.js
Labels: Ready For Review, bug fix

#1079 Updating customError to ErrorBuilder.
  __tests__/data/google_adwords_enhanced_conversions_input.json
  __tests__/data/google_adwords_enhanced_conversions_output.json
  __tests__/data/google_adwords_remarketing_lists_input.json
  __tests__/data/google_adwords_remarketing_lists_output.json
  __tests__/data/pardot_router_input.json
  __tests__/data/pardot_router_output.json
  v0/destinations/google_adwords_enhanced_conversions/transform.js
  v0/destinations/google_adwords_remarketing_lists/transform.js
  v0/destinations/pardot/transform.js
  versionedRouter.js
Labels: testing, Ready For Review, bug fix

#1077 GA: add additional properties
  v0/destinations/ga/transform.js
Labels: enhancement

#1081 FB Pixel: version migration to v13.0
  __tests__/data/facebook_pixel_output.json
  __tests__/data/facebook_pixel_router_output.json
  __tests__/data/fb_router_input.json
  v0/destinations/facebook_pixel/config.js
  v0/destinations/facebook_pixel/transform.js
  v0/destinations/fbpixel/data/FBPIXELCommonConfig.json
Labels: enhancement

#1070 Blueshift - Cloud-mode Integration Onboarding
  __mocks__/axios.js
  __mocks__/data/blueshift/response.json
  __tests__/blueshift.test.js
  __tests__/data/blueshift_input.json
  __tests__/data/blueshift_output.json
  __tests__/data/blueshift_router_input.json
  __tests__/data/blueshift_router_output.json
  jest.config.js
  v0/destinations/blueshift/config.js
  v0/destinations/blueshift/data/blueshiftGroupConfig.json
  v0/destinations/blueshift/data/blueshiftIdentifyConfig.json
  v0/destinations/blueshift/data/blueshiftTrackConfig.json
  v0/destinations/blueshift/transform.js
Labels: new-integration, Ready For Review

#1069 Airship Integration Cloud-mode
  __tests__/airship.test.js
  __tests__/data/airship_input.json
  __tests__/data/airship_output.json
  __tests__/data/airship_router_input.json
  __tests__/data/airship_router_output.json
  v0/destinations/airship/config.js
  v0/destinations/airship/data/airshipGroupConfig.json
  v0/destinations/airship/data/airshipIdentifyConfig.json
  v0/destinations/airship/data/airshipTrackConfig.json
  v0/destinations/airship/transform.js
Labels: new-integration, Ready For Review

#1083 Fix firstName and lastName null by default
  __tests__/data/active_campaign_input.json
  __tests__/data/active_campaign_output.json
  v0/destinations/active_campaign/transform.js
Labels: Ready For Review, bug fix

#1086 rsaas <- master
  CODEOWNERS
  __mocks__/axios.js
  __mocks__/data/blueshift/response.json
  __tests__/airship.test.js
  __tests__/blueshift.test.js
  __tests__/data/active_campaign_input.json
  __tests__/data/active_campaign_output.json
  __tests__/data/airship_input.json
  __tests__/data/airship_output.json
  __tests__/data/airship_router_input.json
  __tests__/data/airship_router_output.json
  __tests__/data/blueshift_input.json
  __tests__/data/blueshift_output.json
  __tests__/data/blueshift_router_input.json
  __tests__/data/blueshift_router_output.json
  __tests__/data/facebook_pixel_output.json
  __tests__/data/facebook_pixel_router_output.json
  __tests__/data/fb_router_input.json
  __tests__/data/warehouse/integration_options_events.js
  __tests__/warehouse.test.js
  jest.config.js
  v0/destinations/active_campaign/transform.js
  v0/destinations/airship/config.js
  v0/destinations/airship/data/airshipGroupConfig.json
  v0/destinations/airship/data/airshipIdentifyConfig.json
  v0/destinations/airship/data/airshipTrackConfig.json
  v0/destinations/airship/transform.js
  v0/destinations/blueshift/config.js
  v0/destinations/blueshift/data/blueshiftGroupConfig.json
  v0/destinations/blueshift/data/blueshiftIdentifyConfig.json
  v0/destinations/blueshift/data/blueshiftTrackConfig.json
  v0/destinations/blueshift/transform.js
  v0/destinations/facebook_pixel/config.js
  v0/destinations/facebook_pixel/transform.js
  v0/destinations/fbpixel/data/FBPIXELCommonConfig.json
  warehouse/identity.js
  warehouse/index.js
  warehouse/v1/util.js
Labels: saas-pr
