Repository rudderlabs/rudder-transformer, pull requests merged in 2022-09, with the labels that each got.

#1369 feature (new integration): Onboard Monday source
  __tests__/data/monday_source_input.json
  __tests__/data/monday_source_output.json
  __tests__/monday_source.test.js
  v0/sources/monday/mapping.json
  v0/sources/monday/transform.js
  v0/sources/monday/util.js
  versionedRouter.js
Labels: new-integration

#1380 feature(new integration): Zapier Onboarding
  __tests__/cdk_postMapper/zapier.test.js
  __tests__/data/zapier_input.json
  __tests__/data/zapier_output.json
  __tests__/utilities/test-utils.js
  __tests__/zapier.test.js
  cdk/zapier/config.yaml
  cdk/zapier/transform.js
  constants/destinationCanonicalNames.js
Labels: new-integration

#1326 feature (new integration): Onboarding RockerBox Integration
  __tests__/data/rockerbox.json
  __tests__/data/rockerbox_router_input.json
  __tests__/data/rockerbox_router_output.json
  __tests__/rockerbox.test.js
  constants/destinationCanonicalNames.js
  v0/destinations/rockerbox/config.js
  v0/destinations/rockerbox/data/RockerboxTrackConfig.json
  v0/destinations/rockerbox/transform.js
Labels: new-integration

#1256 feature(new integration): Pinterest Conversion API onboarding
  __tests__/data/pinterest_tag_input.json
  __tests__/data/pinterest_tag_output.json
  __tests__/data/pinterest_tag_router_input.json
  __tests__/data/pinterest_tag_router_output.json
  __tests__/pinterestConversion.test.js
  constants/destinationCanonicalNames.js
  features.json
  v0/destinations/pinterest_tag/config.js
  v0/destinations/pinterest_tag/data/pinterestCommonConfig.json
  v0/destinations/pinterest_tag/data/pinterestCustomConfig.json
  v0/destinations/pinterest_tag/data/pinterestUserConfig.json
  v0/destinations/pinterest_tag/transform.js
  v0/destinations/pinterest_tag/utils.js
  v0/util/index.js
Labels: new-integration, DO NOT MERGE, Ready for Review

#1393 refactor/(Tiktok_ads): batching revamp
  v0/destinations/tiktok_ads/transform.js
Labels: bug fix

#1352 Add: PATCH option to webhook destination
  __tests__/data/webhook_input.json
  __tests__/data/webhook_output.json
  v0/destinations/webhook/transform.js
Labels: WIP

#1368 feature(new integration): onboarding custify destination
  v0/destinations/custify/config.js
  v0/destinations/custify/data/CUSTIFYGroupConfig.json
  v0/destinations/custify/data/CUSTIFYIdentifyConfig.json
  v0/destinations/custify/data/CUSTIFYTrackConfig.json
  v0/destinations/custify/deleteUsers.js
  v0/destinations/custify/transform.js
Labels: WIP, CLA Pending

#1414 feat(new integration): onboarding mailmodo source
  __tests__/data/mailmodo_source_input.json
  __tests__/data/mailmodo_source_output.json
  __tests__/mailmodo_source.test.js
  v0/sources/mailmodo/mapping.json
  v0/sources/mailmodo/transform.js
Labels: new-integration

#1399 feature(new integration): Woopra destination onboarding
  __tests__/data/woopra.json
  __tests__/data/woopra_router_input.json
  __tests__/data/woopra_router_output.json
  __tests__/woopra.test.js
  constants/destinationCanonicalNames.js
  v0/destinations/woopra/config.js
  v0/destinations/woopra/data/WoopraConfig.json
  v0/destinations/woopra/data/WoopraPageConfig.json
  v0/destinations/woopra/transform.js
  v0/destinations/woopra/utils.js
  v0/util/data/GenericFieldMapping.json
Labels: new-integration, Ready for Review

#1409 refactor/(iterable-batching): revamp batching iterable
  v0/destinations/iterable/transform.js
Labels: DO NOT MERGE

#1413 feature(new integration): User.com destination onboarding
  __mocks__/axios.js
  __mocks__/data/user/response.json
  __mocks__/user.mock.js
  __tests__/data/user.json
  __tests__/data/user_router.json
  __tests__/user.test.js
  constants/destinationCanonicalNames.js
  features.json
  v0/destinations/user/config.js
  v0/destinations/user/data/USERGroupConfig.json
  v0/destinations/user/data/USERIdentifyConfig.json
  v0/destinations/user/data/USERPageConfig.json
  v0/destinations/user/data/USERTrackConfig.json
  v0/destinations/user/transform.js
  v0/destinations/user/utils.js
  v0/util/data/GenericFieldMapping.json
Labels: Ready for Review

#1411 feature(new integration): onboarding mailmodo
  __tests__/data/freshsales.json
  __tests__/data/freshsales_router_output.json
  __tests__/data/mailmodo.json
  __tests__/data/mailmodo_router_input.json
  __tests__/data/mailmodo_router_output.json
  __tests__/mailmodo.test.js
  constants/destinationCanonicalNames.js
  features.json
  v0/destinations/mailmodo/config.js
  v0/destinations/mailmodo/data/identifyConfig.json
  v0/destinations/mailmodo/data/trackConfig.json
  v0/destinations/mailmodo/transform.js
  v0/destinations/mailmodo/utils.js
  v0/util/data/GenericFieldMapping.json
Labels: new-integration

#1407 feat(integration) : add error handling to HubSpot destination
  v0/destinations/hs/config.js
  v0/destinations/hs/transform.js
  v0/destinations/hs/util.js
Labels: enhancement

#1424 feat(signl4): onboarding signl4 cloud mode destination
  __tests__/data/signl4.json
  __tests__/data/signl4_router_input.json
  __tests__/data/signl4_router_output.json
  __tests__/signl4.test.js
  v0/destinations/signl4/config.js
  v0/destinations/signl4/data/Signl4TrackConfig.json
  v0/destinations/signl4/transform.js
  v0/destinations/signl4/utils.js
Labels: new-integration

#1390 fix(appsflyer): event name casing in track payloads
  __tests__/data/af_output.json
  __tests__/data/af_router_output.json
  __tests__/data/tiktok_ads_input.json
  __tests__/data/tiktok_ads_output.json
  v0/destinations/af/data/AFDefaultConfig.json
  v0/destinations/af/transform.js
  v0/destinations/tiktok_ads/config.js
  v0/destinations/tiktok_ads/transform.js
Labels: DO NOT MERGE, DO NOT TOUCH

#1430 feat(serenytics): onboarding serenytics cloud mode destinations
  __tests__/data/serenytics.json
  __tests__/data/serenytics_router_input.json
  __tests__/data/serenytics_router_output.json
  __tests__/serenytics.test.js
  v0/destinations/serenytics/config.js
  v0/destinations/serenytics/data/SerenyticsAliasConfig.json
  v0/destinations/serenytics/data/SerenyticsGroupConfig.json
  v0/destinations/serenytics/data/SerenyticsIdentifyConfig.json
  v0/destinations/serenytics/data/SerenyticsPageScreenConfig.json
  v0/destinations/serenytics/data/SerenyticsTrackConfig.json
  v0/destinations/serenytics/transform.js
  v0/destinations/serenytics/utils.js
Labels: new-integration

#1433 feat(new integration): june cloud mode destination onboarding
  __tests__/data/june.json
  __tests__/data/june_router_input.json
  __tests__/data/june_router_output.json
  __tests__/june.test.js
  constants/destinationCanonicalNames.js
  v0/destinations/clickup/transform.js
  v0/destinations/june/config.js
  v0/destinations/june/data/JuneGroupConfig.json
  v0/destinations/june/data/JuneIdentifyConfig.json
  v0/destinations/june/data/JuneTrackConfig.json
  v0/destinations/june/transform.js
Labels: new-integration

#1437 feature(new integration): Onboarding Engage Cloud Destination
  __tests__/data/engage.json
  __tests__/data/engage_deleteUsers_proxy_input.json
  __tests__/data/engage_deleteUsers_proxy_output.json
  __tests__/data/engage_router_input.json
  __tests__/data/engage_router_output.json
  __tests__/engageMessaging.test.js
  __tests__/proxy.test.js
  constants/destinationCanonicalNames.js
  v0/destinations/engage/config.js
  v0/destinations/engage/data/EngageIdentifyConfig.json
  v0/destinations/engage/data/EngagePageConfig.json
  v0/destinations/engage/deleteUsers.js
  v0/destinations/engage/transform.js
  v0/destinations/engage/utils.js
  v0/destinations/mautic/transform.js
  v0/util/index.js
Labels: new-integration, Ready for Review

#1397 feat(new integration): google adwords offline conversions onboarding
  __tests__/data/google_adwords_offline_conversions.json
  __tests__/data/google_adwords_offline_conversions_proxy_input.json
  __tests__/data/google_adwords_offline_conversions_proxy_output.json
  __tests__/data/google_adwords_offline_conversions_router_input.json
  __tests__/data/google_adwords_offline_conversions_router_output.json
  __tests__/google_adwords_offline_conversions.test.js
  adapters/networkHandlerFactory.js
  features.json
  v0/destinations/google_adwords_offline_conversions/config.js
  v0/destinations/google_adwords_offline_conversions/data/TrackCallConversionsConfig.json
  v0/destinations/google_adwords_offline_conversions/data/TrackClickConversionsConfig.json
  v0/destinations/google_adwords_offline_conversions/transform.js
  v0/destinations/google_adwords_offline_conversions/utils.js
  v0/util/index.js
Labels: new-integration

#1428 feature(new integration): Pinterest Conversion API adding event multiplexing
  __tests__/data/pinterest_tag_output.json
  __tests__/data/pinterest_tag_router_input.json
  __tests__/data/pinterest_tag_router_output.json
  v0/destinations/pinterest_tag/transform.js
  v0/destinations/pinterest_tag/utils.js
Labels: enhancement, Ready for Review

#1415 respond with retriable request error code in case of 5xx
  util/customTransforrmationsStore-v1.js
  util/customTransforrmationsStore.js
  util/fetch.js
  util/trackingPlan.js
  util/utils.js
  versionedRouter.js
Labels: Ready for Review
