Repository rudderlabs/rudder-transformer, pull requests merged in 2022-05, with the labels that each got.

#1148 Bug Fix: Vulnerable packages upgraded
  Dockerfile
  middleware.js
  package-lock.json
  package.json
Labels: dependencies, Vulnerabilities

#1121 bugfix(facebook pixel): timestamp check
  __tests__/data/facebook_pixel_input.json
  __tests__/data/facebook_pixel_output.json
  __tests__/fbpixel.test.js
  v0/destinations/facebook_pixel/transform.js
Labels: Ready For Review, bug fix

#1145 bugfix(FBPixel): compatibility with device mode and ecomm spec
  __tests__/data/facebook_pixel_input.json
  __tests__/data/facebook_pixel_output.json
  v0/destinations/facebook_pixel/transform.js
Labels: Ready For Review, bug fix

#1154 bugfix(fb custom audience): lowerCase() error for number data
  v0/destinations/fb_custom_audience/transform.js
Labels: bug fix

#1159 feature(GA4): add support for page call and validation for timestamp property
  __tests__/data/ga4_input.json
  __tests__/data/ga4_output.json
  __tests__/ga4.test.js
  v0/destinations/ga4/transform.js
  v0/destinations/ga4/utils.js
Labels: enhancement

#1158 feature(Tiktok): add support to take user properties from traits
  __tests__/data/tiktok_ads_input.json
  __tests__/data/tiktok_ads_output.json
  v0/destinations/tiktok_ads/data/TikTokTrack.json
  v0/destinations/tiktok_ads/transform.js
Labels: enhancement

#1179 feature(new integration): New Relic Onboarding
  __tests__/cdk_postMapper/new_relic.test.js
  __tests__/data/new_relic_input.json
  __tests__/data/new_relic_output.json
  __tests__/new_relic.test.js
  __tests__/utilities/test-utils.js
  cdk/new_relic/config.yaml
  cdk/new_relic/mapping/track.yaml
  cdk/new_relic/transform.js
  constants/destinationCanonicalNames.js
Labels: Ready For Review

#1170 feature (new Integration): Snapchat_Conversion(cloud mode) destination Onboarding
  __tests__/data/snapchat_conversion_input.json
  __tests__/data/snapchat_conversion_output.json
  __tests__/data/snapchat_conversion_router_input.json
  __tests__/data/snapchat_conversion_router_output.json
  __tests__/snapchat_conversion.test.js
  features.json
  v0/destinations/snapchat_conversion/config.js
  v0/destinations/snapchat_conversion/data/CheckoutStartedConfig.json
  v0/destinations/snapchat_conversion/data/OrderCompletedConfig.json
  v0/destinations/snapchat_conversion/data/PaymentInfoEnteredConfig.json
  v0/destinations/snapchat_conversion/data/ProductAddedConfig.json
  v0/destinations/snapchat_conversion/data/ProductAddedToWishlistConfig.json
  v0/destinations/snapchat_conversion/data/ProductListViewedConfig.json
  v0/destinations/snapchat_conversion/data/ProductViewedConfig.json
  v0/destinations/snapchat_conversion/data/ProductsSearchedConfig.json
  v0/destinations/snapchat_conversion/data/PromotionClickedConfig.json
  v0/destinations/snapchat_conversion/data/PromotionViewedConfig.json
  v0/destinations/snapchat_conversion/data/SignupConfig.json
  v0/destinations/snapchat_conversion/data/SnapchatCommonConfig.json
  v0/destinations/snapchat_conversion/transform.js
  v0/destinations/snapchat_conversion/util.js
Labels: new-integration

#1181 Additional logs for fetching transformer func with proxy
  util/customTransforrmationsStore-v1.js
  util/customTransforrmationsStore.js
  util/fetch.js
Labels: DO NOT MERGE

#1185 feature(enhancement): GA4- allow custom dimension passthrough
  __tests__/data/ga4_input.json
  __tests__/data/ga4_output.json
  v0/destinations/ga4/transform.js
  v0/destinations/ga4/utils.js
Labels: ready for merge

#1190 bugfix(ga/ga360): nonInteraction can be 0 for enhancedEcoomerce event…
  __tests__/data/ga_input.json
  __tests__/data/ga_output.json
  v0/destinations/ga/transform.js
Labels: bug fix

#1188 feature(new integration): Attentive Tag Cloud mode integration Onboarding
  __tests__/attentive_tag.test.js
  __tests__/data/attentive_tag_input.json
  __tests__/data/attentive_tag_output.json
  __tests__/data/attentive_tag_router_input.json
  __tests__/data/attentive_tag_router_output.json
  constants/destinationCanonicalNames.js
  v0/destinations/attentive_tag/config.js
  v0/destinations/attentive_tag/data/customTrackConfig.json
  v0/destinations/attentive_tag/data/identifyConfig.json
  v0/destinations/attentive_tag/data/itemsConfig.json
  v0/destinations/attentive_tag/data/orderCompletedConfig.json
  v0/destinations/attentive_tag/data/productAddedConfig.json
  v0/destinations/attentive_tag/data/productListViewedConfig.json
  v0/destinations/attentive_tag/data/productViewedConfig.json
  v0/destinations/attentive_tag/transform.js
  v0/destinations/attentive_tag/util.js
Labels: new-integration, WIP

#1164 feat(warehouse): added support for deltalake partition and external location support.
  warehouse/config/ReservedKeywords.json
Labels: Ready For Review

#1192 feature (new Integration): Attentive_Tag(cloud mode) destination Onboarding
  __tests__/data/attentive_tag_input.json
  __tests__/data/attentive_tag_output.json
  v0/destinations/attentive_tag/data/orderCompletedConfig.json
  v0/destinations/attentive_tag/transform.js
  v0/destinations/attentive_tag/util.js
Labels: new-integration, Ready For Review

#1194 feature(enhancement): GA4 update userId's commonConfig
  v0/destinations/ga4/data/GA4CommonConfig.json
Labels: Ready For Review

#1187 feature(new integration): WebEngage Cloud mode integration Onboarding
  __tests__/data/webengage_input.json
  __tests__/data/webengage_output.json
  __tests__/webengage.test.js
  v0/destinations/webengage/config.js
  v0/destinations/webengage/data/WEBENGAGEIdentifyConfig.json
  v0/destinations/webengage/data/WEBENGAGETrackConfig.json
  v0/destinations/webengage/transform.js
  v0/util/data/GenericFieldMapping.json
Labels: new-integration, Ready For Review
