Repository rudderlabs/rudder-transformer, pull requests merged in 2022-02, with the labels that each got.

#959 TikTok Ads Integration
  __tests__/data/tiktok_ads_input.json
  __tests__/data/tiktok_ads_output.json
  __tests__/data/tiktok_ads_router_input.json
  __tests__/data/tiktok_ads_router_output.json
  __tests__/tiktok_ads.test.js
  features.json
  v0/destinations/tiktok_ads/config.js
  v0/destinations/tiktok_ads/data/TikTokTrack.json
  v0/destinations/tiktok_ads/transform.js
Labels: new-integration, Ready For Review

#965 BugFix Amplitude: Removed duplicate fields from event_properties and user_properties
  __tests__/data/am_output.json
  __tests__/data/am_router_output.json
  v0/destinations/am/transform.js
Labels: Ready For Review

#957 Candu new cloud mode integration
  __tests__/candu.test.js
  __tests__/data/candu_input.json
  __tests__/data/candu_output.json
  __tests__/data/candu_router_input.json
  __tests__/data/candu_router_output.json
  features.json
  v0/destinations/candu/config.js
  v0/destinations/candu/data/CanduIdentify.json
  v0/destinations/candu/data/CanduTrack.json
  v0/destinations/candu/transform.js
Labels: Ready For Review

#968 destTransform - correct cluster-enabled logic
  destTransformer.js
Labels: bug fix

#969 Add support for PUT to webhook destination
  __tests__/data/webhook_input.json
  __tests__/data/webhook_output.json
  v0/destinations/webhook/transform.js
Labels: Ready For Review

#971 Enhancement Iterable : Adding support for alias call
  __tests__/data/iterable_input.json
  __tests__/data/iterable_output.json
  v0/destinations/iterable/config.js
  v0/destinations/iterable/data/IterableAliasConfig.json
  v0/destinations/iterable/transform.js
Labels: Ready For Review

#973 SFMC : Added error handling for empty error.response
  v0/destinations/sfmc/transform.js
Labels: bug fix

#976 Amplitude : Adding device_brand in mapping
  __tests__/data/am_input.json
  __tests__/data/am_output.json
  v0/destinations/am/data/AmplitudeDefaultConfig.json
  v0/destinations/am/data/AmplitudeGroupConfig.json
  v0/destinations/am/data/AmplitudeIdentifyConfig.json
  v0/destinations/am/data/AmplitudePageConfig.json
  v0/destinations/am/data/AmplitudeProductActionsConfig.json
  v0/destinations/am/data/AmplitudePromotionClickedConfig.json
  v0/destinations/am/data/AmplitudePromotionViewedConfig.json
  v0/destinations/am/data/AmplitudeRevenueConfig.json
  v0/destinations/am/data/AmplitudeScreenConfig.json
  v0/destinations/am/transform.js
  v0/destinations/am/utils.js
Labels: Ready For Review

#981 Amplitude BugFix: Screen configs updated to fetch device_brand value via getBrand Fucntion
  __tests__/data/am_input.json
  __tests__/data/am_output.json
  v0/destinations/am/data/AmplitudeScreenConfig.json
Labels: Ready For Review

#983 Master -> rudder-saas
  __tests__/data/am_input.json
  __tests__/data/am_output.json
  v0/destinations/am/transform.js
Labels: ready for merge

#984 Facebook Pixel: add event validation check
  __tests__/data/facebook_pixel_input.json
  __tests__/data/facebook_pixel_output.json
  v0/destinations/facebook_pixel/transform.js
Labels: bug

#966 CustomerIO Source - addl. event support
  __tests__/customerio_source.test.js
  __tests__/data/customerio_source_input.json
  __tests__/data/customerio_source_output.json
  v0/sources/customerio/config.js
  v0/sources/customerio/mapping.json
  v0/sources/customerio/transform.js
Labels: enhancement

#985 MP - Update to use the get methods
  v0/destinations/mp/transform.js
Labels: bug fix

#977 Branch - add checks for undefined cases
  __tests__/data/branch_input.json
  __tests__/data/branch_output.json
  __tests__/data/branch_router_input.json
  __tests__/data/branch_router_output.json
  v0/destinations/branch/transform.js
Labels: bug

#989 Change: events to event
  v0/sources/webhook/transform.js
Labels: Ready For Review

#988 added if statement to check if total tags is more than 100, then for …
  v0/destinations/active_campaign/transform.js
Labels: DO NOT MERGE

#990 VDM-Amplitude: added visual mapper for am
  __tests__/data/am_input.json
  __tests__/data/am_output.json
  v0/destinations/am/transform.js
Labels: WIP, DO NOT MERGE

#1001 Mixpanel: eliminate removeUndefinedAndNullValues function
  v0/destinations/mp/transform.js
Labels: WIP, bug fix

#1000 Active Campaign - fix invalid json issue and add case for empty err.response
  __tests__/data/active_campaign_output.json
  v0/destinations/active_campaign/transform.js
  v0/destinations/active_campaign/util.js
Labels: bug

#860 Pardot : with oauth and initial implementation
  __mocks__/data/pardot/proxy_response.json
  __mocks__/network.js
  __tests__/data/pardot_proxy_input.json
  __tests__/data/pardot_proxy_output.json
  __tests__/data/pardot_router_input.json
  __tests__/data/pardot_router_output.json
  __tests__/pardot.test.js
  __tests__/proxy.test.js
  adapters/networkHandlerFactory.js
  features.json
  util/cluster.js
  v0/destinations/pardot/config.js
  v0/destinations/pardot/data/PardotIdentify.json
  v0/destinations/pardot/transform.js
  v0/destinations/pardot/util.js
  v0/util/constant.js
  versionedRouter.js
Labels: Ready For Review, ready for merge

#1009 fb custom audience: erroneous field delete
  __tests__/data/fb_custom_audience_input.json
  __tests__/data/fb_custom_audience_output.json
  __tests__/data/fb_custom_audience_router_input.json
  __tests__/data/fb_custom_audience_router_output.json
  v0/destinations/fb_custom_audience/config.js
  v0/destinations/fb_custom_audience/transform.js
Labels: bug fix

#1006 Active Campaign: add support to get more than 20 fields
  __mocks__/data/active_campaigns/response.json
  v0/destinations/active_campaign/transform.js
Labels: WIP, bug fix

#1005 bugfix-amplitude:added-validation-for-track-event
  v0/destinations/am/transform.js
Labels: Ready For Review

#975 Upgrade node
  Dockerfile
  buildspec.dev.yml
  buildspec.master.yml
  buildspec.saas.yml
  buildspec.saasdev.yml
  buildspec.yml
  versionedRouter.js
Labels: DO NOT MERGE
