Repository rudderlabs/rudder-transformer, pull requests merged in 2022-07, with the labels that each got.

#1066 GoogleSheets router batching support
  __tests__/data/googlesheets_output.json
  __tests__/data/googlesheets_router_input.json
  __tests__/data/googlesheets_router_output.json
  __tests__/googlesheets.test.js
  features.json
  v0/destinations/googlesheets/transform.js
Labels: Ready for Review

#1260 feature (new integration): Onboarding Vero Integration
  __tests__/data/vero.json
  __tests__/data/vero_router_input.json
  __tests__/data/vero_router_output.json
  __tests__/vero.test.js
  constants/destinationCanonicalNames.js
  v0/destinations/vero/config.js
  v0/destinations/vero/data/VeroAliasConfig.json
  v0/destinations/vero/data/VeroIdentifyConfig.json
  v0/destinations/vero/data/VeroSimpleConfig.json
  v0/destinations/vero/data/VeroTrackConfig.json
  v0/destinations/vero/transform.js
Labels: new-integration, Ready for Review

#1268 bugfix(integration): customerio - support for track on anon event
  __tests__/data/customerio_output.json
  v0/destinations/customerio/transform.js
Labels: bug fix

#1270 feature(integration): GA4 - page call enhancement to take its properties from context
  __tests__/data/ga4.json
  v0/destinations/ga4/config.js
  v0/destinations/ga4/data/GA4PageConfig.json
  v0/destinations/ga4/transform.js
Labels: enhancement

#1267 enhancement(integration): Mixpanel event mapping update for track
  __tests__/data/mp_input.json
  __tests__/data/mp_output.json
  __tests__/data/mp_router_output.json
  __tests__/mixpanel.test.js
  v0/destinations/mp/config.js
  v0/destinations/mp/data/MPEventPropertiesConfig.json
  v0/destinations/mp/data/MPIdentifyConfig.json
  v0/destinations/mp/data/MPProfilePropertiesAndroid.json
  v0/destinations/mp/transform.js
Labels: Ready for Review

#1275 bugfix(integration): CustomerIO - Revert changes from PR #1191
  __tests__/data/customerio_input.json
  __tests__/data/customerio_output.json
  v0/destinations/customerio/transform.js
Labels: bug fix

#1282 bugfix(CFD): Facebook Pixel error handling
  __tests__/data/facebook_pixel_input.json
  __tests__/data/facebook_pixel_output.json
  v0/destinations/facebook_pixel/transform.js
Labels: Ready for Review, bug fix

#1285 feature(new feature): Adjust- adding partner parameters
  __tests__/data/adj_input.json
  __tests__/data/adj_output.json
  v0/destinations/adj/transform.js
Labels: Ready for Review

#1278 feature(Klaviyo): Updating API calls
  __mocks__/axios.js
  __mocks__/klaviyo.mock.js
  __tests__/data/klaviyo.json
  __tests__/data/klaviyo_input.json
  __tests__/data/klaviyo_output.json
  __tests__/data/klaviyo_router_input.json
  __tests__/data/klaviyo_router_output.json
  __tests__/klaviyo.test.js
  v0/destinations/klaviyo/data/KlaviyoGroup.json
  v0/destinations/klaviyo/transform.js
  v0/destinations/klaviyo/util.js
Labels: DO NOT MERGE

#1303 bugfix(integration): GA Reverting validation for size
  __tests__/data/ga_input.json
  __tests__/data/ga_output.json
  v0/destinations/ga/transform.js
Labels: bug fix
