Repository rudderlabs/rudder-transformer, pull requests merged in 2022-10, with the labels that each got.

#1472 fix(integration): Engage
  __tests__/data/engage.json
  __tests__/data/engage_router_input.json
  __tests__/data/engage_router_output.json
  v0/destinations/engage/utils.js
Labels: Ready for Review

#1449 feat(new integration): onboarding mailjet
  __tests__/data/mailjet.json
  __tests__/data/mailjet_batch.json
  __tests__/data/mailjet_router.json
  __tests__/mailjet.test.js
  constants/destinationCanonicalNames.js
  features.json
  v0/destinations/mailjet/config.js
  v0/destinations/mailjet/data/MailJetIdentifyConfig.json
  v0/destinations/mailjet/transform.js
  v0/destinations/mailjet/utils.js
Labels: Ready for Review

#1452 feature(mailjet): onboarding mailjet source
  __tests__/data/mailjet_source.json
  __tests__/mailjet_source.test.js
  v0/sources/mailjet/mapping.json
  v0/sources/mailjet/transform.js
Labels: Ready for Review

#1462 feat(integration): onboard Facebook Offline Conversions destination
  __tests__/data/facebook_offline_conversions.json
  __tests__/data/facebook_offline_conversions_router.json
  __tests__/facebook_offline_conversions.test.js
  features.json
  v0/destinations/facebook_offline_conversions/config.js
  v0/destinations/facebook_offline_conversions/data/FbOfflineConversionsTrackConfig.json
  v0/destinations/facebook_offline_conversions/transform.js
  v0/destinations/facebook_offline_conversions/utils.js
Labels: Ready for Review

#1440 hotfix(integration): snapchat_conversion - bring event name to a common ground before comparing
  __tests__/data/snapchat_conversion.json
  v0/destinations/snapchat_conversion/transform.js
Labels: enhancement

#1489 feat/(klaviyo): adding custom traits support in profile updation request
  __tests__/data/klaviyo.json
  __tests__/data/klaviyo_router_output.json
  v0/destinations/klaviyo/transform.js
Labels: Ready for Review

#1499 feat(new feature) facebook offline conversions destination
  __tests__/data/facebook_offline_conversions.json
  __tests__/data/facebook_offline_conversions_router.json
  v0/destinations/facebook_offline_conversions/utils.js
Labels: Ready for Review

#1473 feat(new integration) : Onboarding Refiner Destination
  __tests__/data/refiner.json
  __tests__/data/refiner_router.json
  __tests__/refiner.test.js
  features.json
  v0/destinations/refiner/config.js
  v0/destinations/refiner/transform.js
  v0/destinations/refiner/utils.js
Labels: Ready for Review

#1495 feat(new integration) : onboarding refiner source
  __tests__/data/refiner_source.json
  __tests__/refiner_source.test.js
  v0/sources/refiner/groupMapping.json
  v0/sources/refiner/identifyMapping.json
  v0/sources/refiner/trackMapping.json
  v0/sources/refiner/transform.js
Labels: Ready for Review

#1509 fix: refiner source
  v0/sources/refiner/transform.js
Labels: Ready for Review

#1510 fix: refiner destination group call email value
  __tests__/data/refiner.json
  __tests__/data/refiner_router.json
  v0/destinations/refiner/utils.js
Labels: Ready for Review

#1501 fix: skip adding Id field to salesforce payload
  __tests__/data/salesforce_input.json
  __tests__/data/salesforce_output.json
  v0/destinations/salesforce/transform.js
Labels: Ready for Review

#1496 fix: posthog group update
  __tests__/data/posthog.json
  v0/destinations/posthog/config.js
  v0/destinations/posthog/data/PHGroupConfig.json
  v0/destinations/posthog/data/PHGroupConfigOld.json
  v0/destinations/posthog/transform.js
Labels: Ready for Review, bug fix

#1455 refactor(destination): added log and change returned error during searching objects for retl sources to debug chatpay
  __tests__/data/hs_input.json
  __tests__/data/hs_output.json
  v0/destinations/hs/util.js
Labels: Stale

#1517 fix[ hubspot ] :: simplifying lookup field operation
  __tests__/data/hs_input.json
  __tests__/data/hs_output.json
  __tests__/data/hs_router_input.json
  __tests__/data/hs_router_output.json
  v0/destinations/hs/util.js
Labels: enhancement, Ready for Review

#1500 feat(integration): onboarding gainsight px source
  __tests__/data/gainsightpx_source.json
  __tests__/gpx_source.test.js
  v0/sources/gainsightpx/config.js
  v0/sources/gainsightpx/data/customMapping.json
  v0/sources/gainsightpx/data/engagementMapping.json
  v0/sources/gainsightpx/data/featureMatchMapping.json
  v0/sources/gainsightpx/data/feedbackMapping.json
  v0/sources/gainsightpx/data/identifyMapping.json
  v0/sources/gainsightpx/data/segmentIOMapping.json
  v0/sources/gainsightpx/data/segmentMapping.json
  v0/sources/gainsightpx/data/surveyMapping.json
  v0/sources/gainsightpx/transform.js
  v0/sources/gainsightpx/utils.js
Labels: new-integration, Ready for Review
