Repository rudderlabs/rudder-transformer, pull requests merged in 2022-12, with the labels that each got.

#1598 feat(destination): cache eviction in salesforce
  __mocks__/data/salesforce/proxy_response.json
  __tests__/data/proxy_input.json
  __tests__/data/proxy_output.json
  __tests__/data/salesforce_proxy_input.json
  __tests__/data/salesforce_proxy_output.json
  __tests__/data/salesforce_router_metadata_input.json
  __tests__/data/salesforce_router_metadata_output.json
  __tests__/proxy.test.js
  __tests__/salesforce.test.js
  adapters/network.js
  v0/destinations/salesforce/config.js
  v0/destinations/salesforce/networkHandler.js
  v0/destinations/salesforce/transform.js
  v0/destinations/salesforce/utils.js
Labels: enhancement, Ready for Review

#1604 feat(integrations): update primary email for zendesk
  __mocks__/data/zendesk/response.json
  __tests__/data/zendesk_input.json
  __tests__/data/zendesk_output.json
  v0/destinations/zendesk/transform.js
Labels: enhancement, Ready for Review

#1596 feat(clevertap): onboarding clevertap transformer proxy
  __mocks__/data/clevertap/proxy_response.json
  __mocks__/network.js
  __tests__/data/clevertap_proxy_input.json
  __tests__/data/clevertap_proxy_output.json
  __tests__/proxy.test.js
  v0/destinations/clevertap/config.js
  v0/destinations/clevertap/networkHandler.js
Labels: Ready for Review

#1589 feat(destination): onboard awin integration
  __tests__/awin.test.js
  __tests__/data/awin.json
  constants/destinationCanonicalNames.js
  v0/destinations/awin/config.js
  v0/destinations/awin/data/trackConfig.json
  v0/destinations/awin/transform.js
  v0/destinations/awin/utils.js
Labels: new-integration

#1612 feat(destination): onboard persistIq
  __tests__/data/persistiq.json
  __tests__/data/persistiq_router.json
  __tests__/persistiq.test.js
  v0/destinations/persistiq/config.js
  v0/destinations/persistiq/data/persistIqIdentifyConfig.json
  v0/destinations/persistiq/transform.js
  v0/destinations/persistiq/util.js
Labels: new-integration, Ready for Review

#1614 feat: onboard olark source
  __tests__/data/olark_source.json
  __tests__/olark_source.test.js
  v0/sources/olark/groupMapping.json
  v0/sources/olark/trackMapping.json
  v0/sources/olark/transform.js
  v0/sources/olark/util.js
Labels: Ready for Review

#1590 feat(destination): add groupId support as groupKey in mixpanel
  __tests__/data/mp_input.json
  __tests__/data/mp_output.json
  v0/destinations/mp/transform.js
Labels: enhancement

#1626 fix: email not required for update call
  __tests__/data/persistiq.json
  v0/destinations/persistiq/data/persistIqIdentifyConfig.json
  v0/destinations/persistiq/transform.js
Labels: Ready for Review

#1628 fix(destination): empty params fix in awin
  v0/destinations/awin/utils.js
Labels: bug fix

#1617 feat: onboard ga4 hybrid mode
  src/constants/destinationCanonicalNames.js
  src/v0/destinations/ga4/transform.js
Labels: Ready for Review

#1656 test: fix generic proxy test suite failures
  src/versionedRouter.js
  test/__tests__/data/proxy_output.json
Labels: Error refactor

#1658 refactor: use new error types
  src/v0/util/regulation-api.js
Labels: Error refactor

#1665 feat: refactor new error types (ga360, gainsight, gainsight_px, google_cloud_function, googlepubsnub)
  src/v0/destinations/ga360/transform.js
  src/v0/destinations/gainsight/transform.js
  src/v0/destinations/gainsight/util.js
  src/v0/destinations/gainsight_px/transform.js
  src/v0/destinations/gainsight_px/util.js
  src/v0/destinations/google_cloud_function/util.js
  src/v0/destinations/googlepubsub/transform.js
  test/__tests__/data/ga360_output.json
  test/__tests__/data/google_cloud_function_router_output.json
Labels: Ready for Review, Error refactor

#1649 feat: refactor new error types (awin, blueshift, bqstream, branch, braze)
  src/v0/destinations/awin/transform.js
  src/v0/destinations/blueshift/transform.js
  src/v0/destinations/bqstream/transform.js
  src/v0/destinations/bqstream/util.js
  src/v0/destinations/branch/transform.js
  src/v0/destinations/braze/networkHandler.js
  src/v0/destinations/braze/transform.js
Labels: Ready for Review, Error refactor

#1668 feat: onboard ga4 hybrid mode
  src/constants/destinationCanonicalNames.js
  src/v0/destinations/ga4/transform.js
Labels: Ready for Review

#1651 feat: refactor new error types (custify, customerio, delighted, engage, eventbridge)
  src/v0/destinations/custify/deleteUsers.js
  src/v0/destinations/custify/transform.js
  src/v0/destinations/custify/util.js
  src/v0/destinations/customerio/transform.js
  src/v0/destinations/delighted/transform.js
  src/v0/destinations/delighted/util.js
  src/v0/destinations/engage/deleteUsers.js
  src/v0/destinations/engage/transform.js
  src/v0/destinations/eventbridge/transform.js
  test/__tests__/data/engage_router_output.json
Labels: Ready for Review, Error refactor

#1669 feat: new error types for destinations(mailmodo, mailchimp, lytics, leanplum, lambda)
  src/v0/destinations/lambda/transform.js
  src/v0/destinations/leanplum/transform.js
  src/v0/destinations/lytics/transform.js
  src/v0/destinations/mailchimp/transform.js
  src/v0/destinations/mailchimp/utils.js
  src/v0/destinations/mailmodo/transform.js
  test/__tests__/data/mailchimp_batch_output.json
  test/__tests__/data/mailchimp_output.json
  test/__tests__/data/mailchimp_router_output.json
  test/__tests__/data/mailmodo.json
  test/__tests__/data/mailmodo_router_output.json
Labels: Ready for Review, Error refactor

#1638 feat: new error types for user.com destination
  src/v0/destinations/user/transform.js
  src/v0/destinations/user/utils.js
  test/__tests__/data/user.json
Labels: Ready for Review, Error refactor

#1661 feat: new error types for destinations(profitwell, posthog, postgres, pinterest_tag, personalize)
  src/v0/destinations/personalize/transform.js
  src/v0/destinations/pinterest_tag/transform.js
  src/v0/destinations/pinterest_tag/utils.js
  src/v0/destinations/posthog/transform.js
  src/v0/destinations/profitwell/transform.js
  src/v0/destinations/profitwell/utils.js
  test/__tests__/data/personalize_output.json
  test/__tests__/data/pinterest_tag_output.json
  test/__tests__/data/profitwell_output.json
Labels: Ready for Review, Error refactor

#1666 feat: new error types for destinations(persistiq, pardot, one_signal, ometria, mssql)
  src/v0/destinations/ometria/networkResponseHandler.js
  src/v0/destinations/ometria/transform.js
  src/v0/destinations/one_signal/transform.js
  src/v0/destinations/one_signal/util.js
  src/v0/destinations/pardot/networkHandler.js
  src/v0/destinations/pardot/transform.js
  src/v0/destinations/persistiq/transform.js
  src/v0/destinations/persistiq/util.js
  test/__tests__/data/one_signal.json
  test/__tests__/data/pardot_router_output.json
  test/__tests__/data/persistiq.json
  test/__tests__/data/persistiq_router.json
Labels: Ready for Review, Error refactor

#1667 feat: new error types for destinations(mixpanel, monetate, monday, moengage, minio)
  src/v0/destinations/moengage/transform.js
  src/v0/destinations/monday/transform.js
  src/v0/destinations/monday/util.js
  src/v0/destinations/monetate/transform.js
  src/v0/destinations/mp/deleteUsers.js
  src/v0/destinations/mp/transform.js
  src/v0/destinations/mp/util.js
  test/__tests__/data/moengage_output.json
  test/__tests__/data/monday.json
  test/__tests__/data/monetate_output.json
  test/__tests__/data/mp_output.json
  test/__tests__/deleteUsers/data/mp/handler_output.json
Labels: Ready for Review, Error refactor

#1671 feat: new error types for destinations(kustomer, kochava, klaviyo, kissmetrics, keen)
  src/v0/destinations/keen/transform.js
  src/v0/destinations/kissmetrics/transform.js
  src/v0/destinations/klaviyo/transform.js
  src/v0/destinations/klaviyo/util.js
  src/v0/destinations/kochava/transform.js
  src/v0/destinations/kustomer/transform.js
  src/v0/destinations/kustomer/util.js
  test/__tests__/data/keen_output.json
  test/__tests__/data/klaviyo.json
Labels: Ready for Review, Error refactor

#1659 feat: new error types for destinations (rockerbox, revenue_cat, redis, refiner)
  src/v0/destinations/redis/transform.js
  src/v0/destinations/refiner/transform.js
  src/v0/destinations/revenue_cat/transform.js
  src/v0/destinations/rockerbox/transform.js
  test/__tests__/data/revenue_cat_output.json
  test/__tests__/data/rockerbox.json
Labels: Ready for Review, Error refactor

#1654 feat: new error types for destinations (tiktok_ads, statsig, splitio, snowflake)
  src/v0/destinations/splitio/transform.js
  src/v0/destinations/statsig/transform.js
  src/v0/destinations/tiktok_ads/transform.js
  test/__tests__/data/splitio_output.json
  test/__tests__/data/tiktok_ads_output.json
Labels: Ready for Review, Error refactor

#1655 feat: new error types for destinations (snapchat_custom_audience, snapchat_conversion, slack, singular, signl4)
  src/v0/destinations/signl4/transform.js
  src/v0/destinations/singular/transform.js
  src/v0/destinations/singular/util.js
  src/v0/destinations/slack/transform.js
  src/v0/destinations/snapchat_conversion/transform.js
  src/v0/destinations/snapchat_custom_audience/networkHandler.js
  src/v0/destinations/snapchat_custom_audience/transform.js
  src/v0/destinations/snapchat_custom_audience/utils.js
  test/__tests__/data/signl4.json
  test/__tests__/data/signl4_router_output.json
  test/__tests__/data/singular.json
  test/__tests__/data/slack_output.json
  test/__tests__/data/slack_router_output.json
  test/__tests__/data/snapchat_conversion.json
  test/__tests__/data/snapchat_conversion_router_output.json
  test/__tests__/data/snapchat_custom_audience.json
  test/__tests__/data/snapchat_custom_audience_proxy_output.json
Labels: Ready for Review, Error refactor

#1670 feat: refactor new error types (google_adwords_enhanced_conversion, google_adwords_offline_conversion, google_adwords_remarketing_lists, heap, googlesheets
  src/v0/destinations/google_adwords_enhanced_conversions/networkHandler.js
  src/v0/destinations/google_adwords_enhanced_conversions/transform.js
  src/v0/destinations/google_adwords_offline_conversions/networkHandler.js
  src/v0/destinations/google_adwords_offline_conversions/transform.js
  src/v0/destinations/google_adwords_offline_conversions/utils.js
  src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js
  src/v0/destinations/google_adwords_remarketing_lists/transform.js
  src/v0/destinations/googlesheets/transform.js
  src/v0/destinations/heap/transform.js
  test/__tests__/data/google_adwords_enhanced_conversions_output.json
  test/__tests__/data/google_adwords_enhanced_conversions_router_output.json
  test/__tests__/data/google_adwords_offline_conversions.json
  test/__tests__/data/google_adwords_offline_conversions_proxy_output.json
  test/__tests__/data/google_adwords_remarketing_lists_output.json
Labels: Error refactor

#1672 feat: refactor new error types (hs, indicative, itercom, iterable, drip)
  src/v0/destinations/drip/transform.js
  src/v0/destinations/drip/util.js
  src/v0/destinations/hs/HSTransform-v1.js
  src/v0/destinations/hs/HSTransform-v2.js
  src/v0/destinations/hs/transform.js
  src/v0/destinations/hs/util.js
  src/v0/destinations/indicative/transform.js
  src/v0/destinations/intercom/deleteUsers.js
  src/v0/destinations/intercom/transform.js
  src/v0/destinations/iterable/transform.js
  test/__tests__/data/hs_output.json
  test/__tests__/data/indicative_output.json
  test/__tests__/data/iterable_output.json
Labels: Error refactor

#1642 feat: new error types for sources (gainsightpx, iterable, mailmodo, monday, shopify)
  src/v0/sources/gainsightpx/transform.js
  src/v0/sources/iterable/transform.js
  src/v0/sources/mailmodo/transform.js
  src/v0/sources/monday/transform.js
  src/v0/sources/shopify/transform.js
  src/v0/sources/shopify/util.js
Labels: Ready for Review, Error refactor

#1645 feat: new error types for destinations (webhook, wootric, woopra, yahoo_dsp, zendesk)
  src/v0/destinations/webhook/transform.js
  src/v0/destinations/woopra/transform.js
  src/v0/destinations/wootric/transform.js
  src/v0/destinations/wootric/util.js
  src/v0/destinations/yahoo_dsp/transform.js
  src/v0/destinations/yahoo_dsp/util.js
  src/v0/destinations/zendesk/transform.js
  test/__tests__/data/woopra.json
  test/__tests__/data/woopra_router_output.json
  test/__tests__/data/wootric.json
  test/__tests__/data/wootric_router_output.json
  test/__tests__/data/yahoo_dsp_output.json
  test/__tests__/data/zendesk_output.json
Labels: Ready for Review, Error refactor

#1650 feat: refactor new error types (campaign_manager, candu, canny, clevertap, confluent_cloud)
  src/v0/destinations/campaign_manager/networkHandler.js
  src/v0/destinations/campaign_manager/transform.js
  src/v0/destinations/candu/transform.js
  src/v0/destinations/canny/transform.js
  src/v0/destinations/canny/util.js
  src/v0/destinations/clevertap/deleteUsers.js
  src/v0/destinations/clevertap/transform.js
  src/v0/destinations/confluent_cloud/transform.js
  test/__tests__/data/campaign_manager_router_output.json
Labels: Error refactor

#1639 feat: add new error types ( active_campaign, adjust, adobe_analytics, appsflyer, airship)
  src/v0/destinations/active_campaign/transform.js
  src/v0/destinations/active_campaign/util.js
  src/v0/destinations/adj/transform.js
  src/v0/destinations/adobe_analytics/transform.js
  src/v0/destinations/af/deleteUsers.js
  src/v0/destinations/af/transform.js
  src/v0/destinations/airship/transform.js
  test/__tests__/data/airship_output.json
Labels: Ready for Review, Error refactor

#1674 feat: new error types for destinations(marketo, marketo_static_list, marketo_bulk_upload)
  src/v0/destinations/marketo/networkHandler.js
  src/v0/destinations/marketo/transform.js
  src/v0/destinations/marketo/util.js
  src/v0/destinations/marketo_bulk_upload/fetchJobStatus.js
  src/v0/destinations/marketo_bulk_upload/fileUpload.js
  src/v0/destinations/marketo_bulk_upload/poll.js
  src/v0/destinations/marketo_bulk_upload/transform.js
  src/v0/destinations/marketo_bulk_upload/util.js
  src/v0/destinations/marketo_static_list/networkHandler.js
  src/v0/destinations/marketo_static_list/transform.js
  src/v0/destinations/marketo_static_list/util.js
  test/__tests__/data/marketo_bulk_upload_fileUpload_output.json
  test/__tests__/data/marketo_bulk_upload_output.json
  test/__tests__/data/marketo_bulk_upload_poll_output.json
  test/__tests__/data/marketo_router_output.json
  test/__tests__/data/marketo_static_list.json
  test/__tests__/data/marketo_static_list_proxy_output.json
  test/__tests__/data/marketo_static_list_router_output.json
Labels: Ready for Review, Error refactor

#1660 feat: add new errorTypes (firehose, freshsales, freshmarketer, ga, ga4)
  src/v0/destinations/firehose/transform.js
  src/v0/destinations/freshmarketer/transform.js
  src/v0/destinations/freshmarketer/utils.js
  src/v0/destinations/freshsales/transform.js
  src/v0/destinations/freshsales/utils.js
  src/v0/destinations/ga/deleteUsers.js
  src/v0/destinations/ga/networkHandler.js
  src/v0/destinations/ga/transform.js
  src/v0/destinations/ga/utils.js
  src/v0/destinations/ga4/networkHandler.js
  src/v0/destinations/ga4/transform.js
  src/v0/destinations/ga4/utils.js
  test/__tests__/data/ga4.json
  test/__tests__/data/ga_output.json
Labels: Error refactor

#1648 feat: refactor new error types ( amplitude, algolia, appcues, attentive_tag, attribution, autopilot)
  src/cdk/autopilot/transform.js
  src/v0/destinations/algolia/transform.js
  src/v0/destinations/algolia/util.js
  src/v0/destinations/am/deleteUsers.js
  src/v0/destinations/am/transform.js
  src/v0/destinations/appcues/transform.js
  src/v0/destinations/attentive_tag/transform.js
  src/v0/destinations/attentive_tag/util.js
  src/v0/destinations/attribution/transform.js
  src/v0/destinations/autopilot/transform.js
  test/__tests__/data/algolia_router_output.json
Labels: Error refactor

#1675 fix: heap test cases
  src/v0/util/index.js
Labels: Ready for Review, Error refactor

#1629 fix(destination): follow ecommerce spec in tiktok_ads
  src/v0/destinations/tiktok_ads/data/TikTokTrack.json
  src/v0/destinations/tiktok_ads/transform.js
  test/__tests__/data/tiktok_ads_input.json
  test/__tests__/data/tiktok_ads_output.json
Labels: bug fix

#1677 feat: refactor-dcm_floodlight-cdk-errorTypes
  src/cdk/dcm_floodlight/transform.js
  test/__tests__/data/dcm_floodlight_output.json
  test/__tests__/data/june_router_output.json
Labels: Ready for Review, Error refactor

#1634 feat(destination): onboard pipedream as event stream source
  src/v0/sources/pipedream/config.js
  src/v0/sources/pipedream/transform.js
  src/v0/sources/pipedream/util.js
  test/__tests__/data/pipedream_source.json
  test/__tests__/pipedream_source.test.js
Labels: new-integration, Ready for Review

#1678 fix: proxy test cases
  src/adapters/utils/networkUtils.js
  src/v0/destinations/azure_event_hub/transform.js
  src/v0/destinations/braze/networkHandler.js
  src/v0/destinations/clevertap/networkHandler.js
  src/v0/destinations/confluent_cloud/transform.js
  src/v0/destinations/facebook_pixel/networkHandler.js
  src/v0/destinations/google_adwords_enhanced_conversions/networkHandler.js
  src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js
  src/v0/destinations/kafka/transform.js
  src/v0/destinations/marketo/networkHandler.js
  src/v0/destinations/marketo/util.js
  src/v0/destinations/marketo_static_list/networkHandler.js
  src/v0/destinations/pardot/networkHandler.js
  src/v0/destinations/salesforce/networkHandler.js
  src/v0/destinations/salesforce/transform.js
  src/v0/destinations/salesforce/utils.js
  src/v0/destinations/snapchat_custom_audience/networkHandler.js
  test/__tests__/data/braze_proxy_output.json
  test/__tests__/data/clevertap_proxy_output.json
  test/__tests__/data/facebook_pixel_proxy_output.json
  test/__tests__/data/google_adwords_enhanced_conversions_proxy_output.json
  test/__tests__/data/google_adwords_remarketing_lists_proxy_output.json
  test/__tests__/data/marketo_proxy_output.json
  test/__tests__/data/marketo_static_list_proxy_output.json
  test/__tests__/data/pardot_proxy_output.json
  test/__tests__/data/salesforce_proxy_output.json
  test/__tests__/data/snapchat_custom_audience_proxy_output.json
Labels: Ready for Review, Error refactor

#1676 feat: refactor router transform implementation
  src/cdk/v2/handler.js
  src/v0/destinations/am/transform.js
  src/v0/destinations/wootric/transform.js
  src/v0/util/errorTypes/base.js
  src/v0/util/index.js
  src/versionedRouter.js
Labels: WIP, Error refactor

#1680 chore: refactor all instances of previous error types
  src/cdk/autopilot/transform.js
  src/util/errorNotifier/bugsnag.js
  src/v0/destinations/af/transform.js
  src/v0/destinations/autopilot/transform.js
  src/v0/destinations/facebook_pixel/transform.js
  src/v0/sources/customerio/transform.js
  src/warehouse/identity.js
  src/warehouse/index.js
  src/warehouse/util.js
  src/warehouse/v1/util.js
  test/__tests__/warehouse.test.js
Labels: Error refactor

#1682 fix: user deletion test cases
  test/__tests__/deleteUsers/data/af/handler_output.json
  test/__tests__/deleteUsers/data/am/handler_output.json
  test/__tests__/deleteUsers/data/braze/handler_output.json
  test/__tests__/deleteUsers/data/clevertap/handler_output.json
  test/__tests__/deleteUsers/data/engage/handler_output.json
  test/__tests__/deleteUsers/data/ga/handler_output.json
  test/__tests__/deleteUsers/data/intercom/handler_output.json
Labels: Ready for Review, Error refactor

#1636 feat(destination): map the usertraits for all events in Posthog
  src/v0/destinations/posthog/data/PHAliasConfig.json
  src/v0/destinations/posthog/data/PHGroupConfigOld.json
  src/v0/destinations/posthog/data/PHIdentifyConfig.json
  src/v0/destinations/posthog/data/PHPageConfig.json
  src/v0/destinations/posthog/data/PHScreenConfig.json
  src/v0/destinations/posthog/data/PHTrackConfig.json
  src/v0/destinations/posthog/transform.js
  test/__tests__/data/posthog.json
  test/__tests__/data/posthog_router.json
Labels: enhancement

#1684 feat: router tranform refacor for destinations (batch - 1)
  src/v0/destinations/tiktok_ads/transform.js
  src/v0/destinations/trengo/transform.js
  src/v0/destinations/user/transform.js
  src/v0/destinations/userlist/transform.js
  src/v0/destinations/vero/transform.js
  src/v0/destinations/webengage/transform.js
  src/v0/destinations/webhook/transform.js
  src/v0/destinations/woopra/transform.js
  src/v0/destinations/yahoo_dsp/transform.js
  src/v0/destinations/zendesk/transform.js
  src/v0/util/index.js
  test/__tests__/data/woopra_router_output.json
Labels: Ready for Review, Error refactor

#1685 feat: router tranform refacor for destinations (batch - 2)
  src/v0/destinations/salesforce/transform.js
  src/v0/destinations/sendgrid/transform.js
  src/v0/destinations/serenytics/transform.js
  src/v0/destinations/sfmc/transform.js
  src/v0/destinations/shynet/transform.js
  src/v0/destinations/signl4/transform.js
  src/v0/destinations/singular/transform.js
  src/v0/destinations/slack/transform.js
  src/v0/destinations/snapchat_conversion/transform.js
  src/v0/destinations/snapchat_custom_audience/transform.js
  src/v0/destinations/splitio/transform.js
  test/__tests__/data/signl4_router_output.json
  test/__tests__/data/slack_router_output.json
Labels: Ready for Review, Error refactor

#1686 feat: router tranform refacor for destinations (batch - 3)
  src/v0/destinations/kissmetrics/transform.js
  src/v0/destinations/klaviyo/transform.js
  src/v0/destinations/kochava/transform.js
  src/v0/destinations/kustomer/transform.js
  src/v0/destinations/leanplum/transform.js
  src/v0/destinations/lytics/transform.js
  src/v0/destinations/mailchimp/transform.js
  src/v0/destinations/mailjet/transform.js
  src/v0/destinations/mailmodo/transform.js
  src/v0/destinations/marketo/transform.js
  src/v0/destinations/marketo_bulk_upload/transform.js
  src/v0/destinations/marketo_static_list/transform.js
  src/v0/destinations/mautic/transform.js
  src/v0/destinations/moengage/transform.js
  src/v0/destinations/monday/transform.js
  src/v0/destinations/monetate/transform.js
  src/v0/destinations/mp/transform.js
  src/v0/destinations/ometria/transform.js
  src/v0/destinations/one_signal/transform.js
  src/v0/destinations/pardot/transform.js
  src/v0/destinations/persistiq/transform.js
  src/v0/destinations/personalize/transform.js
  src/v0/destinations/pinterest_tag/transform.js
  src/v0/destinations/posthog/transform.js
  src/v0/destinations/profitwell/transform.js
  src/v0/destinations/refiner/transform.js
  src/v0/destinations/rockerbox/transform.js
  test/__tests__/data/mautic_router_output.json
  test/__tests__/data/pinterest_tag_router_output.json
Labels: Ready for Review, Error refactor

#1687 feat: refactor router transformer - 1
  src/v0/destinations/active_campaign/transform.js
  src/v0/destinations/adj/transform.js
  src/v0/destinations/adobe_analytics/transform.js
  src/v0/destinations/af/transform.js
  src/v0/destinations/airship/transform.js
  src/v0/destinations/algolia/transform.js
  src/v0/destinations/am/transform.js
  src/v0/destinations/appcues/transform.js
  src/v0/destinations/attentive_tag/transform.js
  src/v0/destinations/autopilot/transform.js
  src/v0/destinations/awin/transform.js
  src/v0/destinations/blueshift/transform.js
  src/v0/destinations/branch/transform.js
  src/v0/destinations/braze/transform.js
  src/v0/destinations/campaign_manager/transform.js
  src/v0/destinations/candu/transform.js
  src/v0/destinations/canny/transform.js
  src/v0/destinations/clevertap/transform.js
  src/v0/destinations/clickup/transform.js
  src/v0/destinations/custify/transform.js
Labels: Ready for Review, Error refactor

#1688 feat: refactor router transformer - 2
  src/v0/destinations/customerio/transform.js
  src/v0/destinations/delighted/transform.js
  src/v0/destinations/drip/transform.js
  src/v0/destinations/engage/transform.js
  src/v0/destinations/eventbridge/transform.js
  src/v0/destinations/facebook_offline_conversions/transform.js
  src/v0/destinations/facebook_pixel/transform.js
  src/v0/destinations/factorsai/transform.js
  src/v0/destinations/fb/transform.js
  src/v0/destinations/firehose/transform.js
Labels: Ready for Review, Error refactor

#1689 feat: refactor router transformer - 3
  src/v0/destinations/freshmarketer/transform.js
  src/v0/destinations/freshsales/transform.js
  src/v0/destinations/ga/transform.js
  src/v0/destinations/ga360/transform.js
  src/v0/destinations/gainsight/transform.js
  src/v0/destinations/gainsight_px/transform.js
  src/v0/destinations/google_adwords_enhanced_conversions/transform.js
  src/v0/destinations/google_adwords_offline_conversions/transform.js
  src/v0/destinations/google_adwords_remarketing_lists/transform.js
  src/v0/destinations/google_cloud_function/transform.js
Labels: Ready for Review, Error refactor

#1690 feat: refactor router transformer - 4
  src/v0/destinations/fb_custom_audience/transform.js
  src/v0/destinations/googlepubsub/transform.js
  src/v0/destinations/googlesheets/transform.js
  src/v0/destinations/heap/transform.js
  src/v0/destinations/hs/transform.js
  src/v0/destinations/indicative/transform.js
  src/v0/destinations/intercom/transform.js
  src/v0/destinations/iterable/transform.js
  src/v0/destinations/june/transform.js
  src/v0/destinations/keen/transform.js
  test/__tests__/data/clickup_router_output.json
Labels: Ready for Review, Error refactor

#1691 fix: incorrect usages of error types
  src/cdk/v2/bindings/default.js
  src/cdk/v2/destinations/algolia/procWorkflow.yaml
  src/cdk/v2/destinations/pinterest_tag/procWorkflow.yaml
  src/cdk/v2/utils.js
  src/controllers/destinationProxy.js
  src/v0/destinations/active_campaign/util.js
  src/v0/destinations/braze/networkHandler.js
  src/v0/destinations/canny/util.js
  src/v0/destinations/custify/transform.js
  src/v0/destinations/delighted/transform.js
  src/v0/destinations/drip/transform.js
  src/v0/destinations/engage/transform.js
  src/v0/destinations/eventbridge/transform.js
  src/v0/destinations/fb_custom_audience/transform.js
  src/v0/destinations/ga/networkHandler.js
  src/v0/destinations/ga360/transform.js
  src/v0/destinations/ga4/networkHandler.js
  src/v0/destinations/gainsight_px/transform.js
  src/v0/destinations/gainsight_px/util.js
  src/v0/destinations/google_adwords_enhanced_conversions/transform.js
  src/v0/destinations/marketo/transform.js
  src/v0/destinations/snapchat_custom_audience/transform.js
  src/v0/destinations/trengo/transform.js
  src/v0/util/index.js
  src/versionedRouter.js
  test/__tests__/data/delighted_output.json
  test/__tests__/data/google_adwords_enhanced_conversions_output.json
Labels: Error refactor

#1697 feat: refactor error types - review comments
  src/cdk/v2/destinations/algolia/rtWorkflow.yaml
  src/cdk/v2/destinations/pinterest_tag/rtWorkflow.yaml
  src/v0/destinations/active_campaign/util.js
  src/v0/destinations/adj/transform.js
  src/v0/destinations/adobe_analytics/transform.js
  src/v0/destinations/af/deleteUsers.js
  src/v0/destinations/af/transform.js
  src/v0/destinations/algolia/transform.js
  src/v0/destinations/autopilot/transform.js
  src/v0/destinations/bqstream/util.js
  src/v0/destinations/braze/networkHandler.js
  src/v0/destinations/braze/transform.js
  src/v0/destinations/campaign_manager/networkHandler.js
  src/v0/destinations/campaign_manager/transform.js
  src/v0/destinations/canny/transform.js
  src/v0/destinations/clickup/transform.js
  src/v0/destinations/delighted/util.js
  src/v0/destinations/drip/util.js
  src/v0/destinations/fb_custom_audience/transform.js
  src/v0/destinations/freshsales/utils.js
  src/v0/destinations/ga4/networkHandler.js
  src/v0/destinations/gainsight_px/util.js
  src/v0/destinations/google_adwords_enhanced_conversions/transform.js
  src/v0/destinations/google_adwords_offline_conversions/networkHandler.js
  src/v0/destinations/google_adwords_remarketing_lists/transform.js
  src/v0/destinations/hs/transform.js
  src/v0/destinations/marketo/transform.js
  src/v0/destinations/marketo_static_list/transform.js
  src/v0/destinations/salesforce/transform.js
  src/v0/destinations/snapchat_custom_audience/utils.js
  src/v0/sources/canny/util.js
  src/v0/util/index.js
  test/__tests__/data/braze_proxy_output.json
  test/__tests__/data/pinterest_tag_router_batch_output.json
  test/__tests__/data/pinterest_tag_router_error_output.json
Labels: Ready for Review, Error refactor

#1699 fix: final review issues
  src/v0/destinations/active_campaign/transform.js
  src/v0/destinations/clickup/util.js
  src/versionedRouter.js
Labels: Error refactor

#1698 feat: add error handling for CDK v1
  src/cdk/v1/autopilot/config.yaml
  src/cdk/v1/autopilot/mapping/identify.yaml
  src/cdk/v1/autopilot/mapping/track.yaml
  src/cdk/v1/autopilot/transform.js
  src/cdk/v1/dcm_floodlight/config.js
  src/cdk/v1/dcm_floodlight/config.yaml
  src/cdk/v1/dcm_floodlight/mapping/DCMFloodlightConfig.yaml
  src/cdk/v1/dcm_floodlight/transform.js
  src/cdk/v1/handler.js
  src/cdk/v1/heap/config.yaml
  src/cdk/v1/heap/mapping/identify.yaml
  src/cdk/v1/heap/mapping/track.yaml
  src/cdk/v1/heap/transform.js
  src/cdk/v1/kochava/config.yaml
  src/cdk/v1/kochava/mappings/default.yaml
  src/cdk/v1/kochava/transform.js
  src/cdk/v1/lytics/config.yaml
  src/cdk/v1/lytics/mappings/identify.yaml
  src/cdk/v1/lytics/mappings/page-screen.yaml
  src/cdk/v1/lytics/mappings/track.yaml
  src/cdk/v1/lytics/transform.js
  src/cdk/v1/new_relic/config.yaml
  src/cdk/v1/new_relic/mapping/track.yaml
  src/cdk/v1/new_relic/transform.js
  src/cdk/v1/statsig/config.yaml
  src/cdk/v1/userlist/config.yaml
  src/cdk/v1/userlist/mapping/userlist_default.yaml
  src/cdk/v1/variance/config.yaml
  src/cdk/v1/variance/mappings/default.yaml
  src/cdk/v1/zapier/config.yaml
  src/cdk/v1/zapier/transform.js
  src/versionedRouter.js
  test/__tests__/cdk_postMapper/autopilot.test.js
  test/__tests__/cdk_postMapper/dcm_floodlight.test.js
  test/__tests__/cdk_postMapper/heap.test.js
  test/__tests__/cdk_postMapper/kochava.test.js
  test/__tests__/cdk_postMapper/lytics.test.js
  test/__tests__/cdk_postMapper/new_relic.test.js
  test/__tests__/cdk_postMapper/zapier.test.js
  test/__tests__/utilities/test-utils.js
Labels: Error refactor

#1704 fix: add parsed response in network error
  src/v0/destinations/google_adwords_enhanced_conversions/networkHandler.js
  src/v0/util/errorTypes/abortedError.js
  src/v0/util/errorTypes/base.js
  src/v0/util/errorTypes/invalidAuthTokenError.js
  src/v0/util/errorTypes/networkError.js
  src/v0/util/errorTypes/retryableError.js
  src/v0/util/errorTypes/transformationError.js
  src/v0/util/errorTypes/unauthorizedError.js
  src/versionedRouter.js
  test/__tests__/data/google_adwords_enhanced_conversions_proxy_output.json
  test/__tests__/data/google_adwords_offline_conversions_proxy_output.json
  test/__tests__/data/pardot_proxy_output.json
Labels: Ready for Review, Error refactor

#1705 fix: destinations network error responses
  src/v0/destinations/facebook_pixel/networkHandler.js
  src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js
  test/__tests__/data/facebook_pixel_proxy_output.json
  test/__tests__/data/google_adwords_remarketing_lists_proxy_output.json
Labels: Ready for Review, Error refactor

#1720 fix(clevertap): correction for the max_batch_size value
  src/v0/destinations/clevertap/config.js
Labels: Ready for Review

#1709 feat: ga4 hybrid mode support
  src/constants/destinationCanonicalNames.js
  src/v0/destinations/ga4/transform.js
Labels: enhancement, Ready for Review

#1721 feat: onboard pagerduty source
  src/v0/sources/pagerduty/data/eventMapping.json
  src/v0/sources/pagerduty/data/trackMapping.json
  src/v0/sources/pagerduty/transform.js
  test/__tests__/data/pagerduty_source.json
  test/__tests__/pagerduty.test.js
Labels: new-integration, Ready for Review
