Repository rudderlabs/rudder-transformer, pull requests merged in 2023-07, with the labels that each got.

#2344 fix: convert epoch timestamp into gaoc accepted format
  src/v0/destinations/google_adwords_offline_conversions/data/TrackAddStoreConversionsConfig.json
  src/v0/destinations/google_adwords_offline_conversions/data/TrackCallConversionsConfig.json
  src/v0/destinations/google_adwords_offline_conversions/data/TrackClickConversionsConfig.json
  test/__tests__/data/google_adwords_offline_conversions.json
Labels: Ready for Review, Draft

#2315 fix(ga4): add validation for empty object, arrays, and string values from params
  src/v0/destinations/ga4/transform.js
  src/v0/destinations/ga4/utils.js
  src/v0/destinations/ga4/utils.test.js
  test/__tests__/data/ga4.json
Labels: Ready for Review

#2331 chore: added coverage for ts files
  .github/workflows/report-code-coverage.yml
  jest.config.typescript.js
  jest.default.config.js
  package.json
  sonar-project.properties
Labels: Ready for Review

#2404 fix: for group call send email as identifier when userId is in email format
  src/cdk/v1/new_relic/transform.js
  src/v0/destinations/customerio/util.js
  test/__tests__/data/customerio_input.json
  test/__tests__/data/customerio_output.json
Labels: Ready for Review

#2406 fix: facebook pixel parity with device mode
  src/v0/destinations/facebook_pixel/utils.js
  src/v0/destinations/facebook_pixel/utils.test.js
  test/__tests__/data/facebook_pixel_output.json
Labels: bug fix

#2407 fix: add changes for braze app id
  src/constants/destinationCanonicalNames.js
  src/v0/destinations/braze/braze.util.test.js
  src/v0/destinations/braze/transform.js
  src/v0/destinations/braze/util.js
  test/__tests__/data/braze_input.json
  test/__tests__/data/braze_output.json
Labels: enhancement

#2204 feat: sessionId stitching
  src/util/prometheus.js
  src/util/redis/redisConnector.js
  src/util/redis/redisConnector.test.js
  src/util/redis/testData/shopify_source.json
  src/v0/sources/shopify/shopify.util.test.js
  src/v0/sources/shopify/shopify_redis.util.test.js
  src/v0/sources/shopify/transform.js
  src/v0/sources/shopify/util.js
  test/__mocks__/data/sources/shopify/response.json
  test/__mocks__/redis.js
  test/__tests__/data/shopify.json
Labels: DO NOT MERGE, Ready for Review
