Repository rudderlabs/rudder-transformer, pull requests merged in 2023-03, with the labels that each got.

#1908 fix(fb pixel): zp mapping and external_id
  src/v0/destinations/facebook_pixel/data/FBPIXELUserDataConfig.json
  src/v0/destinations/facebook_pixel/transform.js
  src/v0/destinations/facebook_pixel/utils.js
  test/__tests__/data/facebook_pixel_input.json
  test/__tests__/data/facebook_pixel_output.json
  test/__tests__/data/facebook_pixel_router_input.json
  test/__tests__/data/facebook_pixel_router_output.json
Labels: Ready for Review

#1845 fix(ga4): product array issue
  src/v0/destinations/ga4/config.js
  src/v0/destinations/ga4/data/GA4CartViewedConfig.json
  src/v0/destinations/ga4/data/GA4CheckoutStartedConfig.json
  src/v0/destinations/ga4/data/GA4CheckoutStepCompleted.json
  src/v0/destinations/ga4/data/GA4OrderCompletedConfig.json
  src/v0/destinations/ga4/data/GA4OrderRefundedConfig.json
  src/v0/destinations/ga4/data/GA4PaymentInfoEnteredConfig.json
  src/v0/destinations/ga4/data/GA4ProductAddedConfig.json
  src/v0/destinations/ga4/data/GA4ProductAddedToWishlistConfig.json
  src/v0/destinations/ga4/data/GA4ProductRemovedConfig.json
  src/v0/destinations/ga4/data/GA4ProductViewedConfig.json
  src/v0/destinations/ga4/data/GA4PromotionClickedConfig.json
  src/v0/destinations/ga4/data/GA4PromotionViewedConfig.json
  src/v0/destinations/ga4/transform.js
  src/v0/destinations/ga4/utils.js
  test/__tests__/data/ga4.json
Labels: bug fix

#1904 fix: client_id mapping for ga4
  src/v0/destinations/ga4/transform.js
  test/__tests__/data/ga4.json
Labels: Ready for Review

#1903 fix: remove ga4 identify call support for cloud mode and treat identify call event as track events (login, sign_up and generate_lead)
  src/v0/destinations/ga4/config.js
  src/v0/destinations/ga4/data/GA4GenerateLeadConfig.json
  src/v0/destinations/ga4/data/GA4LoginSignupConfig.json
  src/v0/destinations/ga4/transform.js
  test/__tests__/data/ga4.json
Labels: Ready for Review

#1909 feat: mautic: support self hosted instance
  src/v0/destinations/mautic/transform.js
  src/v0/destinations/mautic/utils.js
  test/__tests__/data/mautic.json
  test/__tests__/data/mautic_router_input.json
  test/__tests__/data/mautic_router_output.json
Labels: Ready for Review

#1910 fix(slack): handlebars error handling
  src/v0/destinations/slack/transform.js
  test/__tests__/data/slack_input.json
  test/__tests__/data/slack_output.json
Labels: bug fix

#1919 fix(util): getDestinationExternalIDObjectForRetl funciton
  src/v0/util/index.js
Labels: bug fix

#1942 fix(firehose): handle undefined message type
  src/v0/destinations/firehose/transform.js
Labels: bug fix

#1932 fix(fb pixel): ecomm
  src/constants/destinationCanonicalNames.js
  src/v0/destinations/facebook_pixel/transform.js
  src/v0/destinations/facebook_pixel/utils.js
  test/__tests__/data/facebook_pixel_input.json
  test/__tests__/data/facebook_pixel_output.json
  test/v0/destinations/facebook_pixel/transform.test.js
Labels: ecomm

#1957 feat: add default action source
  src/v0/destinations/facebook_pixel/config.js
  src/v0/destinations/facebook_pixel/transform.js
  src/v0/destinations/facebook_pixel/utils.js
  test/__tests__/data/facebook_pixel_input.json
  test/__tests__/data/facebook_pixel_output.json
  test/__tests__/data/facebook_pixel_router_output.json
Labels: enhancement

#1949 fix: added products array check for iterable destination
  src/v0/destinations/iterable/transform.js
  test/__tests__/data/iterable_input.json
  test/__tests__/data/iterable_output.json
Labels: Ready for Review

#1979 fix: tik-tok ads offline events email array issue
  src/v0/destinations/tiktok_ads_offline_events/transform.js
  test/__tests__/data/tiktok_ads_offline_events.json
Labels: Ready for Review

#1982 fix: ga4 user_properties structure
  src/v0/destinations/ga4/transform.js
  test/__tests__/data/ga4.json
Labels: Ready for Review

#1971 feat(indicative): parse user agent info
  src/v0/destinations/indicative/transform.js
  src/v0/destinations/indicative/utils.js
  test/__tests__/data/indicative_input.json
  test/__tests__/data/indicative_output.json
  test/__tests__/data/indicative_router_output.json
  test/v0/destinations/indicative/utils.test.js
Labels: enhancement

#2001 fix(monday): axios call empty response issue
  src/v0/destinations/monday/util.js
  test/__mocks__/axios.js
  test/__mocks__/data/monday/response.json
  test/__mocks__/monday.mock.js
  test/__tests__/data/monday.json
Labels: Ready for Review

#1998 fix: undefined columnToPropertyMapping config issue
  src/v0/destinations/monday/util.js
  test/__tests__/data/monday.json
Labels: Ready for Review

#2010 fix(gainsignt_px): undefined attributes issue
  src/v0/destinations/gainsight_px/transform.js
  test/__tests__/data/gainsight_px_input.json
  test/__tests__/data/gainsight_px_output.json
Labels: Ready for Review

#2017 fix(customerio): added validations to convert integer to string
  src/v0/destinations/customerio/data/customerIoGroup.json
  test/__tests__/data/customerio_input.json
  test/__tests__/data/customerio_output.json
Labels: Ready for Review
