Repository rudderlabs/rudder-transformer, pull requests merged in 2023-08, with the labels that each got.

#2413 fix: customerIO source bugsnag issue for invalid timestamp
  src/v0/sources/customerio/transform.js
  test/__tests__/data/customerio_source_input.json
  test/__tests__/data/customerio_source_output.json
Labels: Ready for Review

#2424 fix(iterable): batching order issue
  src/v0/destinations/iterable/transform.js
  test/__tests__/data/iterable_router.json
Labels: Ready for Review

#2431 fix(INT-256): handling non float price input for braze purchase events
  src/v0/destinations/braze/braze.util.test.js
  src/v0/destinations/braze/transform.js
  src/v0/destinations/braze/util.js
  test/__tests__/data/braze_output.json
Labels: bug fix

#2448 fix: valid cart_update event extra check
  src/v0/sources/shopify/config.js
  src/v0/sources/shopify/shopify_redis.util.test.js
  src/v0/sources/shopify/util.js
Labels: Ready for Review

#2446 feat(INT-262): added page call support
  src/v0/destinations/june/config.js
  src/v0/destinations/june/data/JuneGroupConfig.json
  src/v0/destinations/june/data/JuneIdentifyConfig.json
  src/v0/destinations/june/data/JunePageConfig.json
  src/v0/destinations/june/data/JuneTrackConfig.json
  src/v0/destinations/june/transform.js
  test/__tests__/data/june.json
  test/__tests__/data/june_router.json
  test/__tests__/data/june_router_input.json
  test/__tests__/data/june_router_output.json
  test/__tests__/june.test.js
Labels: Ready for Review

#2465 chore(deps): bump sonarcloud-github-action from 1.8 to 2.0.0
  .github/workflows/report-code-coverage.yml
Labels: dependencies, github_actions

#2467 chore: remove ENABLE_SWAGGER env
  src/routes/index.ts
Labels: Ready for Review

#2476 feat(june): added page call support
  src/v0/destinations/june/config.js
  src/v0/destinations/june/data/JuneGroupConfig.json
  src/v0/destinations/june/data/JuneIdentifyConfig.json
  src/v0/destinations/june/data/JunePageConfig.json
  src/v0/destinations/june/data/JuneTrackConfig.json
  src/v0/destinations/june/transform.js
  test/__tests__/data/june.json
  test/__tests__/data/june_router.json
  test/__tests__/data/june_router_input.json
  test/__tests__/data/june_router_output.json
  test/__tests__/june.test.js
Labels: Ready for Review

#2483 fix: pr conflicts
  src/v0/destinations/june/data/JunePageConfig.json
Labels: Ready for Review

#2487 feat(INT-162): adding email as fallback to userId
  src/v0/destinations/customerio/util.js
  src/v0/destinations/customerio/util.test.js
  test/__tests__/data/customerio_input.json
  test/__tests__/data/customerio_output.json
Labels: Ready for Review

#2477 fix(iterable): batch job order
  package-lock.json
  package.json
  src/controllers/destination.ts
  src/services/destination/nativeIntegration.ts
  src/v0/destinations/iterable/transform.js
  src/v0/destinations/iterable/util.js
  src/v0/destinations/iterable/util.test.js
  test/__tests__/data/iterable_router.json
  test/__tests__/iterable.test.js
Labels: Ready for Review

#2390 feat(iterable): refactored destination code
  package-lock.json
  package.json
  src/controllers/destination.ts
  src/services/destination/nativeIntegration.ts
  src/v0/destinations/iterable/config.js
  src/v0/destinations/iterable/transform.js
  src/v0/destinations/iterable/util.js
  src/v0/destinations/iterable/util.test.js
  test/__tests__/data/iterable.json
  test/__tests__/data/iterable_input.json
  test/__tests__/data/iterable_output.json
  test/__tests__/data/iterable_router.json
  test/__tests__/data/iterable_router_input.json
  test/__tests__/data/iterable_router_output.json
  test/__tests__/iterable.test.js
Labels: Ready for Review

#2503 chore: removed duplicate context key from june group config
  src/v0/destinations/june/data/JuneGroupConfig.json
Labels: Ready for Review

#2507 feat(posthog): support timestamp mapping from properties
  src/v0/destinations/posthog/transform.js
Labels: Ready for Review, open source

#2508 fix(braze): enable merge behaviour to stitch user data
  src/v0/destinations/braze/transform.js
Labels: Ready for Review, bug fix

#2514 chore: introduced braze partial failure metric
  src/util/prometheus.js
  src/v0/destinations/braze/networkHandler.js
Labels: Ready for Review

#2516 chore: remove personal information from test cases
  src/util/redis/testData/shopify_source.json
  test/__mocks__/data/mautic/response.json
  test/__tests__/data/appcenter_source_input.json
  test/__tests__/data/auth0_source.json
  test/__tests__/data/gainsightpx_source.json
  test/__tests__/data/lemnisk.json
  test/__tests__/data/mailchimp_input.json
  test/__tests__/data/mailchimp_output.json
  test/__tests__/data/mailjet_source.json
  test/__tests__/data/pagerduty_source.json
  test/__tests__/data/pipedream_source.json
  test/__tests__/data/satismeter_source.json
  test/__tests__/data/sendgrid.json
  test/__tests__/data/sfmc_input.json
  test/__tests__/data/sfmc_output.json
  test/__tests__/data/sfmc_router_input.json
  test/__tests__/data/sfmc_router_output.json
  test/__tests__/data/twitter_ads.json
  test/__tests__/data/versioned_processor_pinterest_tag_input.json
  test/__tests__/data/versioned_router_pinterest_tag_input.json
  test/__tests__/data/woopra.json
  test/integrations/destinations/airship/processor/data.ts
  test/integrations/destinations/engage/processor/data.ts
  test/integrations/destinations/engage/router/data.ts
  test/integrations/destinations/mautic/processor/data.ts
  test/integrations/destinations/mautic/router/data.ts
  test/integrations/destinations/posthog/processor/data.ts
  test/integrations/destinations/woopra/processor/data.ts
  test/integrations/destinations/woopra/router/data.ts
Labels: enhancement, Ready for Review

#2505 fix: marketo bulk upload refactor
  src/util/prometheus.js
  src/v0/destinations/marketo_bulk_upload/config.js
  src/v0/destinations/marketo_bulk_upload/fetchJobStatus.js
  src/v0/destinations/marketo_bulk_upload/fileUpload.js
  src/v0/destinations/marketo_bulk_upload/marketo_bulk_upload.util.test.js
  src/v0/destinations/marketo_bulk_upload/poll.js
  src/v0/destinations/marketo_bulk_upload/util.js
  test/__tests__/data/marketo_bulk_upload_fileUpload_output.json
  test/__tests__/data/marketo_bulk_upload_poll_output.json
Labels: bug fix, Error refactor

#2527 chore: add support of ga4 display name
  src/constants/destinationCanonicalNames.js
  test/__tests__/data/ga4.json
Labels: Ready for Review

#2528 chore: added batch test cases for criteo audience
  test/__tests__/criteo_audience.test.js
  test/__tests__/data/criteo_audience.json
Labels: Ready for Review

#2533 chore(INT-507): added support of type conversion for multiplication operation
  src/v0/util/index.js
Labels: Ready for Review

#2535 fix(iterable): squadcast alert
  src/v0/destinations/iterable/util.js
Labels: Ready for Review
