Repository rudderlabs/rudder-transformer, pull requests merged in 2023-10, with the labels that each got.

#2679 feat(ga4): added support of filter user traits
  src/v0/destinations/ga4/transform.js
  src/v0/destinations/ga4/utils.js
  src/v0/destinations/ga4/utils.test.js
Labels: Ready for Review

#2666 fix(garl): partial failure handling
  src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js
  test/__mocks__/data/google_adwords_remarketing_lists/proxy_response.json
Labels: Ready for Review

#2611 feat(integrations): introduced new status codes to suppress or filter events
  src/routes/destination.ts
  src/services/destination/nativeIntegration.ts
  src/services/misc.ts
  src/util/errorNotifier/bugsnag.js
  src/v0/destinations/braze/transform.js
  src/v0/destinations/braze/util.js
  src/v0/destinations/klaviyo/transform.js
  src/v0/destinations/klaviyo/util.js
  src/v0/util/constant.js
  src/v0/util/errorTypes/filteredEventsError.js
  src/v0/util/errorTypes/index.js
  src/v0/util/index.js
  src/v0/util/tags.js
  test/__mocks__/klaviyo.mock.js
  test/__tests__/braze.test.js
  test/__tests__/data/braze_router.json
  test/__tests__/data/braze_router_input.json
  test/__tests__/data/braze_router_output.json
  test/__tests__/data/klaviyo.json
  test/__tests__/data/klaviyo_router.json
  test/__tests__/data/klaviyo_router_input.json
  test/__tests__/data/klaviyo_router_output.json
  test/__tests__/klaviyo.test.js
Labels: Ready for Review, bug fix

#2707 fix(klaviyo): sending error field at root level for suppress events
  src/v0/destinations/klaviyo/transform.js
  test/__tests__/data/klaviyo_router.json
Labels: Ready for Review

#2681 fix: bugsnag event sent as an object for track call
  src/v0/destinations/customerio/util.js
  src/v0/destinations/freshsales/transform.js
  src/v0/destinations/monday/transform.js
  src/v0/destinations/monday/util.js
  src/v0/util/index.js
  test/__tests__/data/customerio_input.json
  test/__tests__/data/customerio_output.json
  test/__tests__/data/freshsales.json
  test/__tests__/data/monday.json
Labels: Ready for Review

#2667 feat: mixpanel gzip support for import endpoint
  src/v0/destinations/mp/util.js
  src/v0/destinations/mp/util.test.js
  test/integrations/destinations/mp/router/data.ts
Labels: enhancement

#2724 fix: fix getFbGenderVal function
  src/v0/util/index.js
  test/__tests__/data/facebook_pixel_input.json
  test/__tests__/data/facebook_pixel_output.json
Labels: bug fix

#2732 fix: salesforce: handle ECONNABORTED error
  src/adapters/utils/networkUtils.js
  test/__mocks__/data/salesforce/proxy_response.json
  test/__tests__/data/salesforce_proxy_input.json
  test/__tests__/data/salesforce_proxy_output.json
Labels: Draft

#2771 feat: add custom utm parameters to mixpanel
  src/v0/destinations/mp/data/MPEventPropertiesConfig.json
  src/v0/destinations/mp/transform.js
  src/v0/destinations/mp/util.js
  src/v0/destinations/mp/util.test.js
  test/integrations/destinations/mp/processor/data.ts
Labels: enhancement
