Repository rudderlabs/rudder-transformer, pull requests merged in 2023-09, with the labels that each got.

#2542 feat(ga4): added support of campaign_details event
  src/v0/destinations/ga4/config.js
  src/v0/destinations/ga4/data/GA4CampaignDetailsConfig.json
  test/__tests__/data/ga4.json
Labels: Ready for Review

#2545 fix(gaoc): custom variables issue
  src/v0/destinations/google_adwords_offline_conversions/networkHandler.js
Labels: Ready for Review

#2414 fix: marketo bulk upload
  src/controllers/bulkUpload.ts
  src/util/prometheus.js
  src/v0/destinations/marketo_bulk_upload/config.js
  src/v0/destinations/marketo_bulk_upload/fetchJobStatus.js
  src/v0/destinations/marketo_bulk_upload/fileUpload.js
  src/v0/destinations/marketo_bulk_upload/marketo_bulk_upload.util.test.js
  src/v0/destinations/marketo_bulk_upload/poll.js
  src/v0/destinations/marketo_bulk_upload/util.js
  test/__tests__/data/marketo_bulk_upload_fileUpload_output.json
  test/__tests__/data/marketo_bulk_upload_jobStatus_output.json
  test/__tests__/data/marketo_bulk_upload_poll_output.json
Labels: bug fix

#2547 fix(marketo-bulk-upload): sonar issues
  CHANGELOG.md
  src/v0/destinations/marketo_bulk_upload/fetchJobStatus.js
  src/v0/destinations/marketo_bulk_upload/util.js
Labels: enhancement

#2552 fix(google_ads_offline_conversions): partial failure status code issue
  src/v0/destinations/google_adwords_offline_conversions/networkHandler.js
Labels: Ready for Review, bug fix

#2559 fix: marketo bulk upload import issue
  src/v0/destinations/marketo_bulk_upload/fileUpload.js
Labels: bug fix

#2570 feat(INT-580): messageId to event_id mapping support
  src/v0/destinations/tiktok_ads/data/TikTokTrack.json
Labels: enhancement, Ready for Review

#2580 fix(bugsnag): alerts
  src/v0/destinations/adobe_analytics/transform.js
  src/v0/destinations/branch/transform.js
  src/v0/destinations/fb/transform.js
Labels: enhancement, Ready for Review

#2595 fix(INT-591): added support of id parameter for update events
  src/v0/destinations/iterable/data/IterableTrackConfig.json
  src/v0/destinations/iterable/data/IterableTrackPurchaseConfig.json
  test/__tests__/data/iterable.json
Labels: Ready for Review

#2602 fix(iterable): updated mappings
  src/v0/destinations/iterable/data/IterableTrackPurchaseConfig.json
Labels: Ready for Review

#2529 feat: onboard launchdarkly audience
  src/cdk/v2/destinations/launchdarkly_audience/config.js
  src/cdk/v2/destinations/launchdarkly_audience/procWorkflow.yaml
  src/cdk/v2/destinations/launchdarkly_audience/utils.js
  src/cdk/v2/destinations/launchdarkly_audience/utils.test.js
  test/__tests__/data/launchdarkly_audience.json
  test/__tests__/launchdarkly_audience-cdk.test.ts
Labels: enhancement, Ready for Review

#2615 fix(redis): add destination_id in the key
  src/v0/destinations/redis/transform.js
  test/__tests__/data/redis_output.json
Labels: DO NOT MERGE

#2575 fix(INT-523): replaced flag with dropdown for datacenter selection
  src/v0/destinations/customerio/transform.js
  test/__tests__/data/customerio_input.json
Labels: Ready for Review

#2563 fix(INT-568): slack send event to event specific channel based on channel webhook
  src/v0/destinations/slack/transform.js
  src/v0/destinations/slack/util.js
  test/__tests__/data/slack_input.json
  test/__tests__/data/slack_output.json
  test/__tests__/slack.test.js
Labels: Ready for Review

#2608 fix(mixpanel): batch event ordering
  src/v0/destinations/iterable/transform.js
  src/v0/destinations/iterable/util.js
  src/v0/destinations/iterable/util.test.js
  src/v0/destinations/mp/transform.js
  src/v0/destinations/mp/util.js
  src/v0/destinations/mp/util.test.js
  src/v0/util/index.js
  src/v0/util/index.test.js
  src/v0/util/testdata/groupEventsByType.json
  test/__tests__/data/mp_router_output.json
Labels: enhancement

#2624 fix: bqstream event ordering fix
  src/v0/destinations/bqstream/transform.js
  src/v0/destinations/bqstream/util.js
  src/v0/destinations/bqstream/util.test.js
  test/integrations/destinations/bqstream/router/data.ts
Labels: enhancement

#2650 feat: add circular reference check in flattern json
  src/v0/util/index.js
  src/v0/util/index.test.js
Labels: enhancement

#2659 fix(iterable): event id mapping
  src/v0/destinations/iterable/data/IterableTrackConfig.json
  src/v0/destinations/iterable/data/IterableTrackPurchaseConfig.json
  test/__tests__/data/iterable.json
Labels: Ready for Review

#2621 feat(iterable): user deletion support
  src/v0/destinations/iterable/deleteUsers.js
  test/deleteUsers/data/iterable/handler_input.json
  test/deleteUsers/data/iterable/handler_output.json
  test/deleteUsers/data/iterable/nw_client_data.json
Labels: Ready for Review

#2631 feat(gaec): partial failures handling
  src/v0/destinations/google_adwords_enhanced_conversions/networkHandler.js
Labels: Ready for Review
