Repository rudderlabs/rudder-transformer, pull requests merged in 2023-01, with the labels that each got.

#1703 feat(destination): onboard pipedream
  src/constants/destinationCanonicalNames.js
  src/v0/destinations/pipedream/transform.js
  src/v0/destinations/webhook/transform.js
  test/__tests__/data/pipedream.json
  test/__tests__/data/pipedream_router.json
  test/__tests__/pipedream.test.js
Labels: new-integration, Ready for Review

#1731 feat(pinterest): add ldp support
  src/cdk/v2/destinations/pinterest_tag/procWorkflow.yaml
  src/v0/destinations/pinterest_tag/data/pinterestCustomConfig.json
  test/__tests__/data/pinterest_tag_input.json
  test/__tests__/data/pinterest_tag_output.json
  test/__tests__/data/pinterest_tag_router_batch_output.json
  test/__tests__/data/pinterest_tag_router_input.json
  test/__tests__/data/pinterest_tag_router_output.json
Labels: enhancement, Ready for Review

#1736 feat: onboard pagerduty destination
  src/constants/destinationCanonicalNames.js
  src/v0/destinations/pagerduty/config.js
  src/v0/destinations/pagerduty/data/pagerdutyAlertEventConfig.json
  src/v0/destinations/pagerduty/data/pagerdutyChangeEventConfig.json
  src/v0/destinations/pagerduty/transform.js
  src/v0/destinations/pagerduty/util.js
  test/__tests__/data/pagerduty.json
  test/__tests__/data/pagerduty_router.json
  test/__tests__/pagerduty.test.js
  test/__tests__/pagerduty_source.test.js
Labels: new-integration, Ready for Review

#1725 feat(destination): onboard discord
  src/v0/destinations/discord/transform.js
  src/v0/destinations/slack/transform.js
  src/v0/destinations/slack/util.js
  test/__tests__/data/discord.json
  test/__tests__/data/discord_router.json
  test/__tests__/discord.test.js
Labels: new-integration, Ready for Review

#1741 feat: appcenter updated to support test events
  src/v0/sources/appcenter/transform.js
  test/__tests__/data/appcenter_source_input.json
  test/__tests__/data/appcenter_source_output.json
Labels: Ready for Review

#1662 feat(new integration): onboarding sendinblue cloud mode destination
  features.json
  src/constants/destinationCanonicalNames.js
  src/v0/destinations/sendinblue/config.js
  src/v0/destinations/sendinblue/data/SendinblueCreateDOIContactConfig.json
  src/v0/destinations/sendinblue/data/SendinblueCreateOrUpdateContactConfig.json
  src/v0/destinations/sendinblue/data/SendinbluePageConfig.json
  src/v0/destinations/sendinblue/data/SendinblueTrackEventConfig.json
  src/v0/destinations/sendinblue/data/SendinblueTrackLinkConfig.json
  src/v0/destinations/sendinblue/data/SendinblueUpdateDOIContactConfig.json
  src/v0/destinations/sendinblue/transform.js
  src/v0/destinations/sendinblue/util.js
  src/v0/util/data/GenericFieldMapping.json
  src/v0/util/index.js
  test/__mocks__/axios.js
  test/__mocks__/data/sendinblue/response.json
  test/__mocks__/sendinblue.mock.js
  test/__tests__/data/sendinblue.json
  test/__tests__/data/sendinblue_router_input.json
  test/__tests__/data/sendinblue_router_output.json
  test/__tests__/sendinblue.test.js
Labels: new-integration, Ready for Review

#1750 fix: user deletion module update
  src/v0/destinations/am/config.js
  src/v0/destinations/am/deleteUsers.js
  src/v0/destinations/braze/config.js
  src/v0/destinations/braze/deleteUsers.js
  src/v0/destinations/clevertap/config.js
  src/v0/destinations/clevertap/deleteUsers.js
  src/v0/destinations/engage/deleteUsers.js
  src/v0/destinations/intercom/deleteUsers.js
  src/v0/destinations/mp/config.js
  src/v0/destinations/mp/deleteUsers.js
  src/v0/destinations/sendgrid/config.js
  src/v0/destinations/sendgrid/deleteUsers.js
  src/v0/util/deleteUserUtils.js
  test/__tests__/deleteUsers/data/am/handler_input.json
  test/__tests__/deleteUsers/data/am/handler_output.json
  test/__tests__/deleteUsers/data/am/nw_client_data.json
  test/__tests__/deleteUsers/data/braze/handler_input.json
  test/__tests__/deleteUsers/data/braze/handler_output.json
  test/__tests__/deleteUsers/data/braze/nw_client_data.json
  test/__tests__/deleteUsers/data/engage/handler_input.json
  test/__tests__/deleteUsers/data/engage/handler_output.json
  test/__tests__/deleteUsers/data/engage/nw_client_data.json
  test/__tests__/deleteUsers/data/intercom/handler_input.json
  test/__tests__/deleteUsers/data/intercom/handler_output.json
  test/__tests__/deleteUsers/data/intercom/nw_client_data.json
  test/__tests__/deleteUsers/data/mp/handler_input.json
  test/__tests__/deleteUsers/data/mp/handler_output.json
  test/__tests__/deleteUsers/data/mp/nw_client_data.json
  test/__tests__/deleteUsers/data/sendgrid/handler_input.json
  test/__tests__/deleteUsers/data/sendgrid/handler_output.json
  test/__tests__/deleteUsers/data/sendgrid/nw_client_data.json
Labels: Ready for Review

#1738 fix(facebook pixel): error code mapping for transformer proxy
  src/v0/destinations/facebook_pixel/networkHandler.js
  test/__tests__/data/facebook_pixel_proxy_output.json
Labels: bug fix

#1759 feat: clientId support added for ga4 hybrid mode
  src/v0/destinations/ga4/transform.js
  src/v0/util/index.js
Labels: enhancement, Ready for Review

#1730 feat: [impact radius] onboard impact radius cloud mode destination
  package-lock.json
  package.json
  src/v0/destinations/impact_radius/config.js
  src/v0/destinations/impact_radius/data/ImpactConversionConfig.json
  src/v0/destinations/impact_radius/data/ImpactPageLoadConfig.json
  src/v0/destinations/impact_radius/transform.js
  src/v0/destinations/impact_radius/util.js
  test/__tests__/data/impact_radius.json
  test/__tests__/data/impact_radius_router.json
  test/__tests__/impact_radius.test.js
Labels: new-integration

#1746 fix(zendesk): remove endpoint global variable
  src/v0/destinations/zendesk/config.js
  src/v0/destinations/zendesk/transform.js
  test/__mocks__/data/zendesk/response.json
  test/__tests__/data/zendesk_input.json
  test/__tests__/data/zendesk_output.json
  test/__tests__/data/zendesk_router_input.json
  test/__tests__/data/zendesk_router_output.json
Labels: bug fix

#1754 fix: destination transformation change from processor to router
  features.json
Labels: enhancement, Ready for Review

#1777 fix: iterable alias call is separated from identify batching
  src/v0/destinations/iterable/transform.js
  test/__tests__/data/iterable_router_output.json
Labels: enhancement, Ready for Review

#1789 feat: sessionId consistency across destinations
  package.json
  src/v0/destinations/airship/data/airshipTrackConfig.json
  src/v0/destinations/ga4/data/GA4IdentifyGroupCommonParamsConfig.json
  src/v0/destinations/ga4/data/GA4TrackPageCommonParamsConfig.json
  src/v0/destinations/gainsight_px/data/GainsightPX_Track.json
  src/v0/destinations/kustomer/data/KustomerPage.json
  src/v0/destinations/kustomer/data/KustomerScreen.json
  src/v0/destinations/kustomer/data/KustomerTrack.json
  src/v0/destinations/personalize/transform.js
  test/__tests__/data/airship_input.json
  test/__tests__/data/airship_output.json
  test/__tests__/data/ga4.json
  test/__tests__/data/kustomer_input.json
  test/__tests__/data/kustomer_output.json
  test/__tests__/data/personalize_input.json
  test/__tests__/data/personalize_output.json
Labels: Ready for Review

#1796 fix(integration): gaoc - fix timestamp format, allow calls without custom var
  src/v0/destinations/google_adwords_offline_conversions/networkHandler.js
  src/v0/destinations/google_adwords_offline_conversions/transform.js
  test/__tests__/data/google_adwords_offline_conversions.json
  test/__tests__/data/google_adwords_offline_conversions_proxy_input.json
  test/__tests__/data/google_adwords_offline_conversions_proxy_output.json
Labels: bug fix

#1787 feat(destination): onboard lemnisk integration
  src/v0/destinations/lemnisk/config.js
  src/v0/destinations/lemnisk/data/LEMNISKDIAPITrackConfig.json
  src/v0/destinations/lemnisk/data/LEMNISKIdentifyConfig.json
  src/v0/destinations/lemnisk/data/LEMNISKPageConfig.json
  src/v0/destinations/lemnisk/data/LEMNISKTrackConfig.json
  src/v0/destinations/lemnisk/transform.js
  src/v0/destinations/lemnisk/utils.js
  test/__tests__/data/lemnisk.json
  test/__tests__/data/lemnisk_router.json
  test/__tests__/lemniskMarketingAutomation.test.js
Labels: new-integration, Ready for Review

#1794 feat: ga4 page calls are discarded if hybrid mode is enabled
  src/v0/destinations/ga4/transform.js
  src/v0/util/errorTypes/index.js
  src/v0/util/errorTypes/unsupportedEventError.js
  src/v0/util/tags.js
Labels: Ready for Review

#1799 fix(integrations): salesforce update error message and error response handler
  src/v0/destinations/salesforce/transform.js
  src/v0/destinations/salesforce/utils.js
  test/__mocks__/data/salesforce/proxy_response.json
  test/__tests__/data/salesforce_proxy_input.json
  test/__tests__/data/salesforce_proxy_output.json
Labels: Ready for Review, Error refactor

#1815 feat(integration): rockerbox - add support for custom properties mapping
  src/v0/destinations/rockerbox/transform.js
  test/__tests__/data/rockerbox.json
Labels: enhancement

#1812 fix: undefined check added for isHybridModeEnabled function
  src/v0/util/index.js
  test/__tests__/__integration_util_test__/isHybridModeEnabled.test.js
  test/__tests__/data/ga4.json
Labels: bug fix

#1805 feat(new integration): onboard optimizely fullstack cloud mode
  src/constants/destinationCanonicalNames.js
  src/v0/destinations/optimizely_fullstack/config.js
  src/v0/destinations/optimizely_fullstack/data/OptimizelyFullStackTrackConfig.json
  src/v0/destinations/optimizely_fullstack/transform.js
  src/v0/destinations/optimizely_fullstack/util.js
  test/__tests__/data/optimizely_fullstack.json
  test/__tests__/data/optimizely_fullstack_router.json
  test/__tests__/optimizely_fullstack.test.js
Labels: new-integration, Ready for Review

#1792 feat(destination): onboard criteo audience
  features.json
  src/constants/destinationCanonicalNames.js
  src/v0/destinations/criteo_audience/config.js
  src/v0/destinations/criteo_audience/networkHandler.js
  src/v0/destinations/criteo_audience/transform.js
  src/v0/destinations/criteo_audience/util.js
  src/v0/util/index.js
  test/__mocks__/axios.js
  test/__mocks__/data/criteo_audience/proxy_response.json
  test/__mocks__/data/criteo_audience/response.json
  test/__mocks__/network.js
  test/__tests__/criteo_audience.test.js
  test/__tests__/data/criteo_audience.json
  test/__tests__/data/criteo_audience_proxy_input.json
  test/__tests__/data/criteo_audience_proxy_output.json
  test/__tests__/data/criteo_audience_router_input.json
  test/__tests__/data/criteo_audience_router_output.json
  test/__tests__/proxy.test.js
Labels: new-integration, Ready for Review

#1833 fix: amplitude check for actionKey before accessing it
  src/v0/destinations/am/transform.js
  test/__tests__/data/am_input.json
  test/__tests__/data/am_output.json
Labels: Ready for Review
