Repository rudderlabs/rudder-transformer, pull requests merged in 2023-11, with the labels that each got.

#2722 feat: introduce v1/source/sourceType endpoint
  src/controllers/source.ts
  src/controllers/util/index.test.ts
  src/controllers/util/index.ts
  src/features.json
  src/types/index.ts
  src/v1/sources/webhook/transform.js
  test/apitests/data_scenarios/source/v0/failure.json
  test/apitests/data_scenarios/source/v0/response_to_caller.json
  test/apitests/data_scenarios/source/v0/successful.json
  test/apitests/data_scenarios/source/v1/failure.json
  test/apitests/data_scenarios/source/v1/pipedream.json
  test/apitests/data_scenarios/source/v1/successful.json
  test/apitests/service.api.test.ts
Labels: Draft

#2746 feat: oauth in salesforce
  src/constants/destinationCanonicalNames.js
  src/features.json
  src/v0/destinations/salesforce/config.js
  src/v0/destinations/salesforce/transform.js
  src/v0/destinations/salesforce/utils.js
  test/integrations/destinations/salesforce/dataDelivery/data.ts
  test/integrations/destinations/salesforce/processor/data.ts
Labels: enhancement

#2786 feat(INT-305): onboard gladly destination
  package-lock.json
  package.json
  src/cdk/v2/destinations/gladly/procWorkflow.yaml
  src/cdk/v2/destinations/gladly/rtWorkflow.yaml
  src/cdk/v2/destinations/gladly/utils.js
  src/cdk/v2/destinations/gladly/utils.test.js
  src/cdk/v2/handler.ts
  src/constants/destinationCanonicalNames.js
  src/features.json
  src/services/destination/cdkV2Integration.ts
  test/integrations/destinations/gladly/network.ts
  test/integrations/destinations/gladly/processor/data.ts
  test/integrations/destinations/gladly/router/data.ts
Labels: Ready for Review

#2820 feat: mixpanel set once feature onboard
  src/v0/destinations/mp/config.js
  src/v0/destinations/mp/data/MPSetOnceConfig.json
  src/v0/destinations/mp/transform.js
  src/v0/destinations/mp/util.js
  src/v0/destinations/mp/util.test.js
  src/v0/util/index.js
  test/integrations/destinations/mp/common.ts
  test/integrations/destinations/mp/processor/data.ts
Labels: Ready for Review

#2852 fix: bug fix for track event
  src/v0/destinations/sfmc/transform.js
  src/v0/destinations/sfmc/transform.test.js
  test/__tests__/data/sfmc_output.json
  test/__tests__/data/sfmc_router_output.json
Labels: Ready for Review, bug fix
