Repository rudderlabs/rudder-transformer, pull requests merged in 2023-02, with the labels that each got.

#1814 feat(mailchimp): add support for track call
  src/v0/destinations/mailchimp/config.js
  src/v0/destinations/mailchimp/data/mailchimpTrackEventConfig.json
  src/v0/destinations/mailchimp/transform.js
  src/v0/destinations/mailchimp/utils.js
  test/__tests__/data/mailchimp_input.json
  test/__tests__/data/mailchimp_output.json
  test/__tests__/data/mailchimp_router_input.json
  test/__tests__/data/mailchimp_router_output.json
Labels: enhancement, Ready for Review

#1822 feat: userId to be converted to string for Router
  src/v0/util/index.js
  src/versionedRouter.js
  test/__tests__/__integration_util_test__/data/checkAndCorrectUserId.json
  test/__tests__/__integration_util_test__/v0_utilities.test.js
Labels: Ready for Review

#1838 feat(integration): rockerbox - allow all properties to be passed over to rockerbox
  src/v0/destinations/rockerbox/config.js
  src/v0/destinations/rockerbox/transform.js
  test/__tests__/data/rockerbox.json
  test/__tests__/data/rockerbox_router_output.json
Labels: enhancement

#1848 test: add unit tests for extractCustomFields function
  test/__tests__/__integration_util_test__/data/extractCustomFields.json
  test/__tests__/__integration_util_test__/v0_utilities.test.js
Labels: enhancement

#1847 feat: shopify - add cart token, order token and checkout token in the Context object
  src/v0/sources/shopify/transform.js
  test/__tests__/data/shopify_source_output.json
Labels: enhancement, WIP

#1857 fix: ga4 userId issue
  src/v0/destinations/ga4/data/GA4CommonConfig.json
  test/__tests__/data/ga4.json
Labels: bug fix

#1863 fix: bugsnag errors
  src/v0/destinations/sendgrid/util.js
  src/v0/destinations/zendesk/transform.js
Labels: bug fix

#1841 fix: refactor subscribe user flow to stop subscribing user without consent
  src/v0/destinations/klaviyo/config.js
  src/v0/destinations/klaviyo/transform.js
  src/v0/destinations/klaviyo/util.js
  test/__tests__/data/klaviyo.json
  test/__tests__/data/klaviyo_router_output.json
Labels: Ready for Review

#1874 fix: incorrect logger import
  src/v0/destinations/snapchat_conversion/util.js
Labels: bug fix

#1869 feat: added customerio group call support
  features.json
  src/v0/destinations/customerio/config.js
  src/v0/destinations/customerio/data/customerIoGroup.json
  src/v0/destinations/customerio/transform.js
  src/v0/destinations/customerio/util.js
  test/__tests__/customerio.test.js
  test/__tests__/data/customerio_input.json
  test/__tests__/data/customerio_output.json
  test/__tests__/data/customerio_router_input.json
  test/__tests__/data/customerio_router_output.json
Labels: Ready for Review

#1902 fix(active-campaign): add check before iterating stored event array
  src/v0/destinations/active_campaign/transform.js
Labels: bug fix
