Repository rudderlabs/rudder-transformer, pull requests merged in 2024-02, with the labels that each got.

#2976 feat(intercom): upgrade intercom version from 1.4 to 2.10
  src/cdk/v2/destinations/intercom/config.js
  src/cdk/v2/destinations/intercom/procWorkflow.yaml
  src/cdk/v2/destinations/intercom/rtWorkflow.yaml
  src/cdk/v2/destinations/intercom/utils.js
  src/cdk/v2/destinations/intercom/utils.test.js
  src/constants/destinationCanonicalNames.js
  src/v0/destinations/intercom/config.js
  src/v0/destinations/intercom/data/INTERCOMGroupConfig.json
  src/v0/destinations/intercom/data/INTERCOMIdentifyConfig.json
  src/v0/destinations/intercom/data/INTERCOMTrackConfig.json
  src/v0/destinations/intercom/deleteUsers.js
  src/v0/destinations/intercom/transform.js
  src/v0/destinations/intercom/util.js
  src/v0/destinations/intercom/util.test.js
  test/integrations/destinations/intercom/dataDelivery/data.ts
  test/integrations/destinations/intercom/deleteUsers/data.ts
  test/integrations/destinations/intercom/network.ts
  test/integrations/destinations/intercom/processor/data.ts
  test/integrations/destinations/intercom/router/data.ts
Labels: Ready for Review

#3023 feat: trade desk real time conversions
  jest.default.config.js
  src/cdk/v2/destinations/the_trade_desk/config.js
  src/cdk/v2/destinations/the_trade_desk/data/TTDCommonConfig.json
  src/cdk/v2/destinations/the_trade_desk/data/TTDItemConfig.json
  src/cdk/v2/destinations/the_trade_desk/rtWorkflow.yaml
  src/cdk/v2/destinations/the_trade_desk/transformConversion.js
  src/cdk/v2/destinations/the_trade_desk/transformRecord.js
  src/cdk/v2/destinations/the_trade_desk/utils.js
  src/cdk/v2/destinations/the_trade_desk/utils.test.js
  src/constants/destinationCanonicalNames.js
  src/constants/index.js
  src/v0/destinations/the_trade_desk/networkHandler.js
  src/v0/util/index.js
  src/v0/util/index.test.js
  test/integrations/destinations/clevertap/dataDelivery/data.ts
  test/integrations/destinations/clickup/processor/data.ts
  test/integrations/destinations/criteo_audience/dataDelivery/data.ts
  test/integrations/destinations/custify/processor/data.ts
  test/integrations/destinations/delighted/processor/data.ts
  test/integrations/destinations/drip/processor/data.ts
  test/integrations/destinations/freshmarketer/processor/data.ts
  test/integrations/destinations/freshsales/processor/data.ts
  test/integrations/destinations/ga/processor/data.ts
  test/integrations/destinations/ga360/processor/data.ts
  test/integrations/destinations/gainsight/processor/data.ts
  test/integrations/destinations/gcs_datalake/processor/data.ts
  test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/data.ts
  test/integrations/destinations/marketo_bulk_upload/processor/data.ts
  test/integrations/destinations/marketo_static_list/dataDelivery/data.ts
  test/integrations/destinations/revenue_cat/processor/data.ts
  test/integrations/destinations/rockerbox/processor/data.ts
  test/integrations/destinations/segment/processor/data.ts
  test/integrations/destinations/snapchat_custom_audience/dataDelivery/data.ts
  test/integrations/destinations/snapchat_custom_audience/processor/data.ts
  test/integrations/destinations/splitio/processor/data.ts
  test/integrations/destinations/the_trade_desk/common.ts
  test/integrations/destinations/the_trade_desk/delivery/data.ts
  test/integrations/destinations/the_trade_desk/network.ts
  test/integrations/destinations/the_trade_desk/router/data.ts
  test/integrations/destinations/tiktok_audience/processor/data.ts
  test/integrations/destinations/vero/processor/data.ts
  test/integrations/destinations/wootric/processor/data.ts
  test/test_reporter/reporter.ts
Labels: new-integration

#3059 fix: trade desk enrichTrackPayload util
  src/cdk/v2/destinations/the_trade_desk/utils.js
  src/cdk/v2/destinations/the_trade_desk/utils.test.js
  test/integrations/destinations/the_trade_desk/router/data.ts
Labels: bug fix

#3038 fix: error handling for auth0 source
  src/v0/sources/auth0/transform.js
  test/__tests__/auth0_source.test.js
  test/__tests__/data/auth0_source.json
Labels: Error refactor

#3064 fix: gaoc batching order
  src/v0/destinations/google_adwords_offline_conversions/transform.js
  src/v0/destinations/mp/transform.js
  src/v0/destinations/mp/util.js
  src/v0/destinations/mp/util.test.js
  src/v0/util/index.js
  src/v0/util/index.test.js
  test/integrations/destinations/google_adwords_offline_conversions/router/data.ts
Labels: bug fix

#3089 fix(ga4): failures not considered with 200 status in events tab
  src/v0/destinations/ga4/networkHandler.js
Labels: Ready for Review

#3097 chore: add requestMethod and module latency labels
  src/cdk/v2/destinations/intercom/utils.js
  src/v0/destinations/braze/braze.util.test.js
  src/v0/destinations/braze/transform.js
  src/v0/destinations/braze/util.js
  src/v0/destinations/clickup/util.js
  src/v0/destinations/custify/deleteUsers.js
  src/v0/destinations/delighted/util.js
  src/v0/destinations/drip/util.js
  src/v0/destinations/engage/deleteUsers.js
  src/v0/destinations/gainsight/util.js
  src/v0/destinations/gainsight_px/util.js
  src/v0/destinations/hs/util.js
  src/v0/destinations/iterable/deleteUsers.js
  src/v0/destinations/kustomer/util.js
  src/v0/destinations/mailchimp/utils.js
  src/v0/destinations/marketo_bulk_upload/fetchJobStatus.js
  src/v0/destinations/marketo_bulk_upload/fileUpload.js
  src/v0/destinations/marketo_bulk_upload/marketo_bulk_upload.util.test.js
  src/v0/destinations/marketo_bulk_upload/poll.js
  src/v0/destinations/marketo_bulk_upload/util.js
  src/v0/destinations/mautic/utils.js
  src/v0/destinations/profitwell/utils.js
  src/v0/destinations/rakuten/networkHandler.js
  src/v0/destinations/salesforce/transform.js
  src/v0/destinations/salesforce/utils.js
  src/v0/destinations/sendgrid/deleteUsers.js
  src/v0/destinations/sendgrid/util.js
  src/v0/destinations/sendinblue/util.js
  src/v0/destinations/sfmc/transform.js
  src/v0/destinations/snapchat_custom_audience/networkHandler.js
  src/v0/destinations/sprig/deleteUsers.js
  src/v0/destinations/the_trade_desk/networkHandler.js
  src/v0/destinations/trengo/transform.js
  src/v0/destinations/yahoo_dsp/util.js
  src/v0/destinations/zendesk/transform.js
Labels: Ready for Review

#3065 feat: add custom property mapping feature for freshsales identify call
  src/v0/destinations/freshsales/transform.js
  src/v0/destinations/freshsales/utils.js
  src/v0/destinations/freshsales/utils.test.js
  src/v0/util/index.js
  src/v0/util/index.test.js
  src/v0/util/testdata/generateExclusionListUsingKeyPaths.json
  test/integrations/destinations/freshsales/processor/data.ts
  test/integrations/destinations/freshsales/router/data.ts
Labels: enhancement

#3061 feat: onboard bluecore integration
  src/cdk/v2/destinations/bluecore/config.js
  src/cdk/v2/destinations/bluecore/data/bluecoreCommonConfig.json
  src/cdk/v2/destinations/bluecore/data/bluecoreIdentifyConfig.json
  src/cdk/v2/destinations/bluecore/data/bluecoreTrackConfig.json
  src/cdk/v2/destinations/bluecore/procWorkflow.yaml
  src/cdk/v2/destinations/bluecore/utils.js
  src/cdk/v2/destinations/bluecore/utils.test.js
  test/integrations/destinations/bluecore/data.ts
  test/integrations/destinations/bluecore/ecommTestData.ts
  test/integrations/destinations/bluecore/identifyTestData.ts
  test/integrations/destinations/bluecore/trackTestData.ts
  test/integrations/destinations/bluecore/validationTestData.ts
  test/integrations/testUtils.ts
Labels: new-integration

#3107 chore: onboard ga4 proxy tests
  test/integrations/destinations/ga4/dataDelivery/data.ts
  test/integrations/destinations/ga4/network.ts
Labels: Ready for Review

#3108 chore: added statuscode stat for user deletion
  src/v0/destinations/af/deleteUsers.js
  src/v0/destinations/am/deleteUsers.js
  src/v0/destinations/braze/deleteUsers.js
  src/v0/destinations/clevertap/deleteUsers.js
  src/v0/destinations/custify/deleteUsers.js
  src/v0/destinations/engage/deleteUsers.js
  src/v0/destinations/intercom/deleteUsers.js
  src/v0/destinations/iterable/deleteUsers.js
  src/v0/destinations/mp/deleteUsers.js
  src/v0/destinations/sendgrid/deleteUsers.js
  src/v0/destinations/sprig/deleteUsers.js
  src/v0/util/tags.js
Labels: Ready for Review

#3129 fix: rakuten: sync property mapping sourcekeys to rudderstack standard spec
  src/cdk/v2/destinations/rakuten/data/propertiesMapping.json
  test/integrations/destinations/rakuten/processor/transformationFailure.ts
Labels: DO NOT UPDATE

#3105 feat: klaviyo profile mapping
  src/v0/destinations/klaviyo/data/KlaviyoIdentify.json
  src/v0/destinations/klaviyo/data/KlaviyoProfile.json
  test/integrations/destinations/klaviyo/processor/identifyTestData.ts
Labels: enhancement

#3134 fix: marketo bulk upload zero and null value allowed
  src/v0/destinations/marketo_bulk_upload/transform.js
  test/integrations/destinations/marketo_bulk_upload/processor/data.ts
Labels: DO NOT UPDATE, DO NOT TOUCH
