Repository rudderlabs/rudder-transformer, pull requests merged in 2024-03, with the labels that each got.

#3096 chore: reddit proxy test refactor
  test/integrations/destinations/reddit/dataDelivery/business.ts
  test/integrations/destinations/reddit/dataDelivery/data.ts
  test/integrations/destinations/reddit/dataDelivery/oauth.ts
  test/integrations/destinations/reddit/delivery/data.ts
Labels: Ready for Review

#3098 feat: add support of custom page/screen event name in mixpanel
  src/v0/destinations/mp/transform.js
  src/v0/destinations/mp/util.js
  src/v0/destinations/mp/util.test.js
  test/integrations/destinations/mp/processor/data.ts
Labels: enhancement

#3122 feat: add Koala destination
  src/cdk/v2/destinations/koala/procWorkflow.yaml
  src/cdk/v2/destinations/koala/rtWorkflow.yaml
  src/constants/destinationCanonicalNames.js
  src/features.json
  test/integrations/destinations/koala/processor/data.ts
  test/integrations/destinations/koala/router/data.ts
Labels: new-integration

#3073 chore: garl proxy test refactor
  test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/business.ts
  test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/data.ts
Labels: Ready for Review

#3088 chore: refactor intercom proxy tests to new component structure
  test/integrations/destinations/intercom/dataDelivery/business.ts
  test/integrations/destinations/intercom/dataDelivery/data.ts
  test/integrations/destinations/intercom/dataDelivery/other.ts
  test/integrations/destinations/intercom/network.ts
Labels: Ready for Review

#3072 chore: gaoc proxy test refactor
  test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/business.ts
  test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/data.ts
  test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/oauth.ts
  test/integrations/destinations/google_adwords_offline_conversions/network.ts
Labels: Ready for Review

#3137 chore: ga4 proxy test refactor
  test/integrations/destinations/ga4/dataDelivery/business.ts
  test/integrations/destinations/ga4/dataDelivery/data.ts
  test/integrations/destinations/ga4/network.ts
Labels: Ready for Review

#3075 fix: fb pixel test case refactor
  src/v0/destinations/facebook_pixel/transform.test.js
  src/v0/destinations/facebook_pixel/utils.test.js
  src/v0/util/facebookUtils/index.js
  src/v0/util/facebookUtils/index.test.js
  test/integrations/destinations/facebook_pixel/processor/configLevelFeaturesTestData.ts
  test/integrations/destinations/facebook_pixel/processor/data.ts
  test/integrations/destinations/facebook_pixel/processor/ecommTestData.ts
  test/integrations/destinations/facebook_pixel/processor/identifyTestData.ts
  test/integrations/destinations/facebook_pixel/processor/pageScreenTestData.ts
  test/integrations/destinations/facebook_pixel/processor/trackTestData.ts
  test/integrations/destinations/facebook_pixel/processor/validationTestData.ts
  test/integrations/testUtils.ts
Labels: enhancement

#3177 chore: gaec proxy test refactor
  src/v0/destinations/google_adwords_enhanced_conversions/networkHandler.js
  test/integrations/destinations/google_adwords_enhanced_conversions/dataDelivery/business.ts
  test/integrations/destinations/google_adwords_enhanced_conversions/dataDelivery/data.ts
  test/integrations/destinations/google_adwords_enhanced_conversions/dataDelivery/oauth.ts
  test/integrations/destinations/google_adwords_enhanced_conversions/network.ts
Labels: Ready for Review

#3167 feat: onboard destination movable ink
  src/cdk/v2/destinations/movable_ink/config.js
  src/cdk/v2/destinations/movable_ink/procWorkflow.yaml
  src/cdk/v2/destinations/movable_ink/rtWorkflow.yaml
  src/features.json
  test/integrations/destinations/movable_ink/common.ts
  test/integrations/destinations/movable_ink/processor/data.ts
  test/integrations/destinations/movable_ink/processor/identify.ts
  test/integrations/destinations/movable_ink/processor/track.ts
  test/integrations/destinations/movable_ink/processor/validation.ts
  test/integrations/destinations/movable_ink/router/data.ts
Labels: new-integration

#3121 feat: consent field support for gaoc for API v15 and upgrade the api version from v14 to v16
  src/constants/destinationCanonicalNames.js
  src/v0/destinations/google_adwords_offline_conversions/config.js
  src/v0/destinations/google_adwords_offline_conversions/transform.js
  src/v0/destinations/google_adwords_offline_conversions/utils.js
  src/v0/destinations/google_adwords_offline_conversions/utils.test.js
  src/v0/destinations/google_adwords_remarketing_lists/config.js
  src/v0/destinations/google_adwords_remarketing_lists/transform.js
  src/v0/util/googleUtils/index.js
  src/v0/util/googleUtils/index.test.js
  test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/business.ts
  test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/oauth.ts
  test/integrations/destinations/google_adwords_offline_conversions/network.ts
  test/integrations/destinations/google_adwords_offline_conversions/processor/data.ts
  test/integrations/destinations/google_adwords_offline_conversions/router/data.ts
Labels: enhancement
