Repository rudderlabs/rudder-transformer, pull requests merged in 2024-07, with the labels that each got.

#3486 feat: onboarding clicksend destination
  src/cdk/v2/destinations/clicksend/config.ts
  src/cdk/v2/destinations/clicksend/procWorkflow.yaml
  src/cdk/v2/destinations/clicksend/rtWorkflow.yaml
  src/cdk/v2/destinations/clicksend/utils.js
  src/cdk/v2/destinations/clicksend/utils.test.js
  src/features.json
  src/v1/destinations/clicksend/networkHandler.js
  test/integrations/destinations/clicksend/commonConfig.ts
  test/integrations/destinations/clicksend/dataDelivery/data.ts
  test/integrations/destinations/clicksend/network.ts
  test/integrations/destinations/clicksend/processor/data.ts
  test/integrations/destinations/clicksend/processor/identify.ts
  test/integrations/destinations/clicksend/processor/track.ts
  test/integrations/destinations/clicksend/router/data.ts
Labels: new-integration

#3241 fix(gainsight): replace myAxios utility with handleHttpRequest utility
  src/features.json
  src/v0/destinations/gainsight/transform.js
  src/v0/destinations/gainsight/util.js
  test/integrations/destinations/gainsight/network.ts
  test/integrations/destinations/gainsight/processor/data.ts
Labels: Ready for Review

#3548 chore(release): pull hotfix-release/v1.71.1 into main
  CHANGELOG.md
  package-lock.json
  package.json
  src/v0/destinations/ga4/utils.js
  src/v0/destinations/ga4_v2/customMappingsHandler.js
  src/v0/destinations/tiktok_ads/config.js
  src/v0/destinations/tiktok_ads/transformV2.js
  test/integrations/destinations/tiktok_ads/processor/data.ts
  test/integrations/destinations/tiktok_ads/router/data.ts
Labels: DO NOT MERGE

#3527 feat: braze source event mapping
  src/v0/sources/braze/eventMapping.json
  src/v1/sources/braze/ignore.json
  src/v1/sources/braze/mapping.json
  src/v1/sources/braze/transform.js
  test/__tests__/braze_source.test.js
  test/__tests__/data/braze_source_input.json
  test/__tests__/data/braze_source_output.json
  test/integrations/sources/braze/common.ts
  test/integrations/sources/braze/data.ts
Labels: enhancement

#3555 feat: onboarding new destination zoho
  src/cdk/v2/destinations/zoho/config.js
  src/cdk/v2/destinations/zoho/rtWorkflow.yaml
  src/cdk/v2/destinations/zoho/transformRecord.js
  src/cdk/v2/destinations/zoho/utils.js
  src/cdk/v2/destinations/zoho/utils.test.js
  src/features.json
  src/v1/destinations/zoho/networkHandler.js
  test/integrations/component.test.ts
  test/integrations/destinations/zoho/common.ts
  test/integrations/destinations/zoho/dataDelivery/business.ts
  test/integrations/destinations/zoho/dataDelivery/data.ts
  test/integrations/destinations/zoho/mocks.ts
  test/integrations/destinations/zoho/network.ts
  test/integrations/destinations/zoho/router/data.ts
  test/integrations/destinations/zoho/router/deletion.ts
  test/integrations/destinations/zoho/router/upsert.ts
Labels: new-integration

#3594 fix: update getConversionActionId function for gaoc
  src/v0/destinations/google_adwords_offline_conversions/utils.js
  test/integrations/destinations/google_adwords_offline_conversions/dataDelivery/oauth.ts
  test/integrations/destinations/google_adwords_offline_conversions/network.ts
Labels: DO NOT MERGE

#3586 fix: added support for ga4 v2 hybrid mode
  src/constants/destinationCanonicalNames.js
  src/v0/destinations/ga4/transform.js
  src/v0/destinations/ga4/utils.js
  src/v0/destinations/ga4_v2/customMappingsHandler.js
  src/v0/destinations/ga4_v2/transform.ts
  test/integrations/destinations/ga4_v2/processor/customMappings.ts
  test/integrations/testUtils.ts
Labels: DO NOT MERGE
