Repository rudderlabs/rudder-transformer, pull requests merged in 2024-01, with the labels that each got.

#2964 feat: move intercom to routerTransform
  src/features.json
Labels: Ready for Review

#2953 fix: for gainsight px only new users to have default signUp date
  src/v0/destinations/gainsight_px/data/GainsightPX_Identify.json
  src/v0/destinations/gainsight_px/transform.js
  test/integrations/destinations/gainsight_px/processor/data.ts
  test/integrations/destinations/gainsight_px/router/data.ts
Labels: bug fix

#2886 feat(sprig): added user deletion support
  src/v0/destinations/sprig/deleteUsers.js
  test/integrations/destinations/sprig/deleteUsers/data.ts
  test/integrations/destinations/sprig/network.ts
Labels: Ready for Review

#2945 fix: enhancement and version upgrade of google ads remarketing list
  src/v0/destinations/google_adwords_remarketing_lists/config.js
  src/v0/destinations/google_adwords_remarketing_lists/networkHandler.js
  src/v0/destinations/google_adwords_remarketing_lists/transform.js
  src/v0/util/googleUtils/index.js
  src/v0/util/googleUtils/index.test.js
  test/__mocks__/data/google_adwords_remarketing_lists/proxy_response.json
  test/integrations/destinations/google_adwords_remarketing_lists/dataDelivery/data.ts
  test/integrations/destinations/google_adwords_remarketing_lists/network.ts
  test/integrations/destinations/google_adwords_remarketing_lists/processor/data.ts
  test/integrations/destinations/google_adwords_remarketing_lists/router/data.ts
Labels: enhancement

#2918 feat: onboard new destination the trade desk
  src/adapters/network.js
  src/cdk/v2/destinations/the_trade_desk/config.js
  src/cdk/v2/destinations/the_trade_desk/rtWorkflow.yaml
  src/cdk/v2/destinations/the_trade_desk/utils.js
  src/cdk/v2/destinations/the_trade_desk/utils.test.js
  src/features.json
  src/v0/destinations/the_trade_desk/networkHandler.js
  test/integrations/destinations/the_trade_desk/common.ts
  test/integrations/destinations/the_trade_desk/delivery/data.ts
  test/integrations/destinations/the_trade_desk/mocks.ts
  test/integrations/destinations/the_trade_desk/network.ts
  test/integrations/destinations/the_trade_desk/router/data.ts
Labels: new-integration

#2911 chore: upgrade @aws-sdk/lib-storage from 3.417.0 to 3.456.0
  package-lock.json
  package.json
Labels: Stale

#3016 fix: fixing network error messages for marketo bulk upload
  src/v0/destinations/marketo_bulk_upload/fileUpload.js
  src/v0/destinations/marketo_bulk_upload/poll.js
  src/v0/destinations/marketo_bulk_upload/util.js
  test/__tests__/data/marketo_bulk_upload_jobStatus_output.json
Labels: enhancement

#3029 fix: deleting access token cache for marketo bulk upload destination
  src/v0/destinations/marketo_bulk_upload/fileUpload.js
  src/v0/destinations/marketo_bulk_upload/marketo_bulk_upload.util.test.js
  src/v0/destinations/marketo_bulk_upload/poll.js
  src/v0/destinations/marketo_bulk_upload/util.js
  test/__tests__/data/marketo_bulk_upload_jobStatus_output.json
Labels: bug fix

#3037 fix: adding map for marketo known values and javascript known values
  src/v0/destinations/marketo_bulk_upload/config.js
  src/v0/destinations/marketo_bulk_upload/marketo_bulk_upload.util.test.js
  src/v0/destinations/marketo_bulk_upload/util.js
Labels: bug fix
