Repository rudderlabs/rudder-transformer, pull requests merged in 2024-04, with the labels that each got.

#3213 feat: consent field support for ga4
  src/v0/destinations/ga4/transform.js
  src/v0/destinations/ga4/utils.js
  src/v0/destinations/ga4/utils.test.js
  src/v0/util/googleUtils/index.js
  src/v0/util/googleUtils/index.test.js
  test/integrations/destinations/ga4/processor/data.ts
Labels: Ready for Review

#3194 feat: onboarding linkedin conversion api
  src/cdk/v2/destinations/linkedin_ads/config.js
  src/cdk/v2/destinations/linkedin_ads/data/linkedinUserInfoConfig.json
  src/cdk/v2/destinations/linkedin_ads/procWorkflow.yaml
  src/cdk/v2/destinations/linkedin_ads/rtWorkflow.yaml
  src/cdk/v2/destinations/linkedin_ads/utils.js
  src/cdk/v2/destinations/linkedin_ads/utils.test.js
  src/features.json
  src/v0/util/data/GenericFieldMapping.json
  src/v1/destinations/linkedin_ads/networkHandler.js
  test/integrations/destinations/linkedin_ads/dataDelivery/business.ts
  test/integrations/destinations/linkedin_ads/dataDelivery/data.ts
  test/integrations/destinations/linkedin_ads/dataDelivery/oauth.ts
  test/integrations/destinations/linkedin_ads/network.ts
  test/integrations/destinations/linkedin_ads/processor/configLevelFeaturesTestData.ts
  test/integrations/destinations/linkedin_ads/processor/data.ts
  test/integrations/destinations/linkedin_ads/processor/trackTestData.ts
  test/integrations/destinations/linkedin_ads/processor/validationTestData.ts
  test/integrations/destinations/linkedin_ads/router/data.ts
  test/integrations/testUtils.ts
Labels: new-integration

#3263 fix: marketo bulk ignore null while checking data type mismatch
  src/v0/destinations/marketo_bulk_upload/marketo_bulk_upload.util.test.js
  src/v0/destinations/marketo_bulk_upload/util.js
Labels: bug fix

#3264 fix: adding check for reserved key words in extract custom fields
  src/v0/util/index.js
  src/v0/util/index.test.js
Labels: bug fix

#3258 fix: hubspot: search for contact using secondary prop
  src/v0/destinations/hs/HSTransform-v2.js
  src/v0/destinations/hs/config.js
  src/v0/destinations/hs/util.js
  src/v0/destinations/hs/util.test.js
  test/integrations/destinations/hs/network.ts
  test/integrations/destinations/hs/router/data.ts
Labels: Ready for Review

#3285 fix: awin product_id mapping backward compatible
  src/v0/destinations/awin/utils.js
Labels: bug fix

#3237 fix(delighted): replace myAxios utility with handleHttpRequest utility
  src/v0/destinations/delighted/util.js
  test/integrations/destinations/delighted/network.ts
  test/integrations/destinations/delighted/processor/data.ts
Labels: Ready for Review

#3250 feat(iterable): component test refactor
  test/integrations/destinations/iterable/processor/aliasTestData.ts
  test/integrations/destinations/iterable/processor/data.ts
  test/integrations/destinations/iterable/processor/identifyTestData.ts
  test/integrations/destinations/iterable/processor/pageScreenTestData.ts
  test/integrations/destinations/iterable/processor/trackTestData.ts
  test/integrations/destinations/iterable/processor/validationTestData.ts
  test/integrations/testUtils.ts
Labels: Ready for Review

#3236 chore: component test refactor for intercom destination
  test/integrations/destinations/intercom/processor/data.ts
  test/integrations/destinations/intercom/processor/groupTestData.ts
  test/integrations/destinations/intercom/processor/identifyTestData.ts
  test/integrations/destinations/intercom/processor/trackTestData.ts
  test/integrations/destinations/intercom/processor/validationTestData.ts
Labels: Ready for Review

#3290 fix: algolia enhancement
  src/cdk/v2/destinations/algolia/procWorkflow.yaml
  src/v0/destinations/algolia/config.js
  src/v0/destinations/algolia/data/AlgoliaTrack.json
  src/v0/destinations/algolia/transform.js
  src/v0/destinations/algolia/util.js
  test/integrations/destinations/algolia/processor/data.ts
Labels: enhancement

#3221 feat(refiner): component test refactor
  test/integrations/destinations/refiner/processor/data.ts
  test/integrations/destinations/refiner/processor/groupTestData.ts
  test/integrations/destinations/refiner/processor/identifyTestData.ts
  test/integrations/destinations/refiner/processor/pageTestData.ts
  test/integrations/destinations/refiner/processor/trackTestData.ts
  test/integrations/destinations/refiner/processor/validationTestData.ts
Labels: Ready for Review

#3325 feat: custom property support AWIN
  src/v0/destinations/awin/transform.js
  src/v0/destinations/awin/utils.js
  src/v0/destinations/awin/utils.test.js
  test/integrations/destinations/awin/data.ts
Labels: enhancement
