Repository rudderlabs/rudder-transformer, pull requests merged in 2024-05, with the labels that each got.

#3334 fix: auth0 error handling for missing userId
  src/v0/sources/auth0/transform.js
  test/__tests__/auth0_source.test.js
  test/__tests__/data/auth0_source.json
  test/integrations/sources/auth0/data.ts
Labels: bug fix

#3148 feat: add slack source
  src/v0/sources/slack/mapping.json
  src/v0/sources/slack/transform.js
  src/v0/sources/slack/util.js
  src/v0/sources/slack/util.test.js
  test/integrations/sources/slack/data.ts
Labels: new-integration

#3318 feat: onboard emersys destination
  src/cdk/v2/destinations/emarsys/config.js
  src/cdk/v2/destinations/emarsys/procWorkflow.yaml
  src/cdk/v2/destinations/emarsys/rtWorkflow.yaml
  src/cdk/v2/destinations/emarsys/utils.js
  src/cdk/v2/destinations/emarsys/utils.test.js
  src/constants/destinationCanonicalNames.js
  src/features.json
  src/services/destination/nativeIntegration.ts
  src/v0/destinations/emarsys/deleteUsers.js
  src/v0/util/deleteUserUtils.js
  src/v1/destinations/emarsys/networkHandler.js
  test/integrations/destinations/emarsys/dataDelivery/data.ts
  test/integrations/destinations/emarsys/deleteUsers/data.ts
  test/integrations/destinations/emarsys/network.ts
  test/integrations/destinations/emarsys/processor/data.ts
  test/integrations/destinations/emarsys/router/data.ts
Labels: new-integration

#3220 feat(ga4): component test refactor
  test/integrations/destinations/ga4/mocks.ts
  test/integrations/destinations/ga4/processor/data.ts
  test/integrations/destinations/ga4/processor/ecomTestData.ts
  test/integrations/destinations/ga4/processor/groupTestData.ts
  test/integrations/destinations/ga4/processor/pageTestData.ts
  test/integrations/destinations/ga4/processor/trackTestData.ts
  test/integrations/destinations/ga4/processor/validationTestData.ts
  test/integrations/testTypes.ts
  test/integrations/testUtils.ts
Labels: Ready for Review

#3428 fix: bugsnag error for emarsys track call
  src/cdk/v2/destinations/emarsys/utils.js
  test/integrations/destinations/emarsys/processor/data.ts
Labels: bug fix
